In [11]:
import cv2
import numpy as np
import math
import time

In [14]:
#cap =cv2.VideoCapture("http://192.168.1.90:8080/video")#http://192.168.1.90:8080
#cap = cv2.VideoCapture("http://10.84.123.48:8080/video")
cap = cv2.VideoCapture("http://10.84.88.194:8080/video")

In [15]:
folder = "C:/Users/Raj/Desktop/Independent Study/calibrate"

In [16]:
counter = 0
while True:
    success, img = cap.read()
    cv2.imshow("im",img)
    
    key = cv2.waitKey(1)    
    if key ==ord("s"):
        counter += 1
        cv2.imwrite(f'{folder}/Image_{time.time()}.jpg',img)
        print(counter)
    elif key ==ord('q'):
        break
cap.release()
cv2.destroyAllWindows()

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54


In [ ]:
cap.release()

In [7]:
cv2.destroyAllWindows()

In [1]:
import numpy as np
import cv2 as cv
import glob
# termination criteria
criteria = (cv.TERM_CRITERIA_EPS + cv.TERM_CRITERIA_MAX_ITER, 30, 0.001)
# prepare object points, like (0,0,0), (1,0,0), (2,0,0) ....,(6,5,0)
objp = np.zeros((6*9,3), np.float32)
objp[:,:2] = np.mgrid[0:9,0:6].T.reshape(-1,2)
# Arrays to store object points and image points from all the images.
objpoints = [] # 3d point in real world space
imgpoints = [] # 2d points in image plane.
images = glob.glob('*.jpg')
for fname in images:
    img = cv.imread(fname)
    cv.imshow("im",img)
    cv.waitKey(1)
    gray = cv.cvtColor(img, cv.COLOR_BGR2GRAY)
    # Find the chess board corners
    ret, corners = cv.findChessboardCorners(gray, (9,6), None)
    print(ret)
    # If found, add object points, image points (after refining them)
    if ret == True:
        print("a")
        objpoints.append(objp)
        corners2 = cv.cornerSubPix(gray,corners, (11,11), (-1,-1), criteria)
        imgpoints.append(corners2)
        # Draw and display the corners
        cv.drawChessboardCorners(img, (9,6), corners2, ret)
        cv.imshow('img', img)
        cv.waitKey(500)
cv.destroyAllWindows()

False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False


In [7]:
cv.destroyAllWindows()

In [12]:
import numpy as np
import cv2 as cv
import glob



################ FIND CHESSBOARD CORNERS - OBJECT POINTS AND IMAGE POINTS #############################

chessboardSize = (9,6)
frameSize = (1440,1080)
path = r"C:/Users/Raj/Desktop/Independent Study/calibrate/new/*.jpg"


# termination criteria
criteria = (cv.TERM_CRITERIA_EPS + cv.TERM_CRITERIA_MAX_ITER, 30, 0.001)


# prepare object points, like (0,0,0), (1,0,0), (2,0,0) ....,(6,5,0)
#objp = np.zeros((chessboardSize[0] * chessboardSize[1], 3), np.float32)
#objp[:,:2] = np.mgrid[0:chessboardSize[0],0:chessboardSize[1]].T.reshape(-1,2)

objp = np.zeros((6*7,3), np.float32)
objp[:,:2] = np.mgrid[0:7,0:6].T.reshape(-1,2)
# objp[:, 0] = np.tile(np.arange(8), 6) * 30
# objp[:, 1] = np.repeat(np.arange(6), 8) * 30
#size_of_chessboard_squares_mm = 27.5
#|objp = objp * size_of_chessboard_squares_mm


# Arrays to store object points and image points from all the images.
objpoints = [] # 3d point in real world space
imgpoints = [] # 2d points in image plane.


#images = glob.glob('*.jpg')
iamges = glob.glob(path)
for image in images:

    img = cv.imread(image)
    gray = cv.cvtColor(img, cv.COLOR_BGR2GRAY)

    # Find the chess board corners
    ret, corners = cv.findChessboardCorners(gray, chessboardSize, None)
    print(ret)
    # If found, add object points, image points (after refining them)
    if ret == True:

        objpoints.append(objp)
        corners2 = cv.cornerSubPix(gray, corners, (11,11), (-1,-1), criteria)
        imgpoints.append(corners)

        # Draw and display the corners
        cv.drawChessboardCorners(img, chessboardSize, corners2, ret)
        cv.imshow('img', img)
        cv.waitKey(100)


cv.destroyAllWindows()




############## CALIBRATION #######################################################

ret, cameraMatrix, dist, rvecs, tvecs = cv.calibrateCamera(objpoints, imgpoints, frameSize, None, None)


############## UNDISTORTION #####################################################

img = cv.imread('C:/Users/Raj/Desktop/Independent Study/Image_1685056464.5000937.jpg')
h,  w = img.shape[:2]
newCameraMatrix, roi = cv.getOptimalNewCameraMatrix(cameraMatrix, dist, (w,h), 1, (w,h))



# Undistort
dst = cv.undistort(img, cameraMatrix, dist, None, newCameraMatrix)

# # crop the image
# x, y, w, h = roi
# dst = dst[y:y+h, x:x+w]
# cv.imwrite('caliResult1.png', dst)



# Undistort with Remapping
# mapx, mapy = cv.initUndistortRectifyMap(cameraMatrix, dist, None, newCameraMatrix, (w,h), 5)
# dst = cv.remap(img, mapx, mapy, cv.INTER_LINEAR)

# # crop the image
# x, y, w, h = roi
# dst = dst[y:y+h, x:x+w]
# cv.imwrite('caliResult2.png', dst)




# Reprojection Error
mean_error = 0

for i in range(len(objpoints)):
    imgpoints2, _ = cv.projectPoints(objpoints[i], rvecs[i], tvecs[i], cameraMatrix, dist)
    error = cv.norm(imgpoints[i], imgpoints2, cv.NORM_L2)/len(imgpoints2)
    mean_error += error

print( "total error: {}".format(mean_error/len(objpoints)) )
np.save("calibration_matrix",cameraMatrix)
np.save("distortion_coefficients", dist)
np.save("new_calibration_matrix",newCameraMatrix)
print("mat:",cameraMatrix)
print("new:",newCameraMatrix)
print("tvec:",tvecs)
print("rvec:",rvecs)

False
False
False
False
False
False


KeyboardInterrupt: 

In [4]:
cv.destroyAllWindows()

In [ ]:

import numpy as np
import cv2
import sys
import time
import cv2.aruco as aruco

def pose_esitmation(frame, matrix_coefficients, distortion_coefficients):

    '''
    frame - Frame from the video stream
    matrix_coefficients - Intrinsic matrix of the calibrated camera
    distortion_coefficients - Distortion coefficients associated with your camera
    return:-
    frame - The frame with the axis drawn on it
    '''

    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    cv2.aruco_dict = cv2.aruco.Dictionary_get(aruco.DICT_4X4_50)
    parameters = cv2.aruco.DetectorParameters_create()


    corners, ids, rejected_img_points = cv2.aruco.detectMarkers(gray, cv2.aruco_dict,parameters=parameters,
        cameraMatrix=matrix_coefficients,
        distCoeff=distortion_coefficients)

        # If markers are detected
    if len(corners) > 0:
        for i in range(0, len(ids)):
            # Estimate pose of each marker and return the values rvec and tvec---(different from those of camera coefficients)
            rvec, tvec, markerPoints = cv2.aruco.estimatePoseSingleMarkers(corners[i], 0.02, matrix_coefficients,
                                                                       distortion_coefficients)
            # Draw a square around the markers
            cv2.aruco.drawDetectedMarkers(frame, corners) 

            # Draw Axis
            cv2.aruco.drawAxis(frame, matrix_coefficients, distortion_coefficients, rvec, tvec, 0.01)  

    return frame

if __name__ == '__main__':

    #aruco_dict_type = ARUCO_DICT[DICT_4X4_50]
    aruco_type = "DICT_4X4_50"
    arucoDict = aruco.Dictionary_get(ARUCO_DICT[aruco_type])
    # Define the parameters for the marker detection
    arucoParams = aruco.DetectorParameters_create()
    #M = None
    
    distortion_coefficients_path ='C:/Users/Raj/Desktop/Independent Study/calibrate/distortion_coefficients.npy'
    calibration_matrix_path = 'C:/Users/Raj/Desktop/Independent Study/calibrate/new_calibration_matrix.npy'
    
    k = np.load(calibration_matrix_path)
    d = np.load(distortion_coefficients_path)

    #video = cv2.VideoCapture(0)
    video =cv2.VideoCapture("http://192.168.1.90:8080/video")
    time.sleep(2.0)

    while True:
        ret, frame = video.read()

        if not ret:
            break
        
        output = pose_esitmation(frame,ARUCO_DUC  k, d)

        cv2.imshow('Estimated Pose', output)

        key = cv2.waitKey(1) & 0xFF
        if key == ord('q'):
            break

    video.release()
    cv2.destroyAllWindows()

In [ ]:
calibration_matrix_path = 'C:/Users/Raj/Desktop/Independent Study/calibrate/calibration_matrix.npy'

# Load the calibration matrix
calibration_matrix = np.load(calibration_matrix_path)

# Use the calibration matrix in your code
# (replace this with your actual code that uses the matrix)
print(calibration_matrix)

In [ ]:
import numpy as np
import cv2.aruco as aruco
import sys
import time
import cv2

ARUCO_DICT = {
	"DICT_4X4_50": cv2.aruco.DICT_4X4_50,
	"DICT_4X4_100": cv2.aruco.DICT_4X4_100,
	"DICT_4X4_250": cv2.aruco.DICT_4X4_250,
	"DICT_4X4_1000": cv2.aruco.DICT_4X4_1000,
	"DICT_5X5_50": cv2.aruco.DICT_5X5_50,
	"DICT_5X5_100": cv2.aruco.DICT_5X5_100,
	"DICT_5X5_250": cv2.aruco.DICT_5X5_250,
	"DICT_5X5_1000": cv2.aruco.DICT_5X5_1000,
	"DICT_6X6_50": cv2.aruco.DICT_6X6_50,
	"DICT_6X6_100": cv2.aruco.DICT_6X6_100,
	"DICT_6X6_250": cv2.aruco.DICT_6X6_250,
	"DICT_6X6_1000": cv2.aruco.DICT_6X6_1000,
	"DICT_7X7_50": cv2.aruco.DICT_7X7_50,
	"DICT_7X7_100": cv2.aruco.DICT_7X7_100,
	"DICT_7X7_250": cv2.aruco.DICT_7X7_250,
	"DICT_7X7_1000": cv2.aruco.DICT_7X7_1000,
	"DICT_ARUCO_ORIGINAL": cv2.aruco.DICT_ARUCO_ORIGINAL,
	"DICT_APRILTAG_16h5": cv2.aruco.DICT_APRILTAG_16h5,
	"DICT_APRILTAG_25h9": cv2.aruco.DICT_APRILTAG_25h9,
	"DICT_APRILTAG_36h10": cv2.aruco.DICT_APRILTAG_36h10,
	"DICT_APRILTAG_36h11": cv2.aruco.DICT_APRILTAG_36h11
}

def aruco_display(corners, ids, rejected, image):
    
	if len(corners) > 0:
		
		ids = ids.flatten()
		
		for (markerCorner, markerID) in zip(corners, ids):
			
			corners = markerCorner.reshape((4, 2))
			(topLeft, topRight, bottomRight, bottomLeft) = corners
			
			topRight = (int(topRight[0]), int(topRight[1]))
			bottomRight = (int(bottomRight[0]), int(bottomRight[1]))
			bottomLeft = (int(bottomLeft[0]), int(bottomLeft[1]))
			topLeft = (int(topLeft[0]), int(topLeft[1]))

			cv2.line(image, topLeft, topRight, (0, 255, 0), 2)
			cv2.line(image, topRight, bottomRight, (0, 255, 0), 2)
			cv2.line(image, bottomRight, bottomLeft, (0, 255, 0), 2)
			cv2.line(image, bottomLeft, topLeft, (0, 255, 0), 2)
			
			cX = int((topLeft[0] + bottomRight[0]) / 2.0)
			cY = int((topLeft[1] + bottomRight[1]) / 2.0)
			cv2.circle(image, (cX, cY), 4, (0, 0, 255), -1)
			
			cv2.putText(image, str(markerID),(topLeft[0], topLeft[1] - 10), cv2.FONT_HERSHEY_SIMPLEX,
				0.5, (0, 255, 0), 2)
			print("[Inference] ArUco marker ID: {}".format(markerID))
			
	return image



def pose_estimation(frame, aruco_dict_type, matrix_coefficients, distortion_coefficients):

    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    aruco_dict = aruco.Dictionary_get(aruco_dict_type)
    parameters = aruco.DetectorParameters_create()


    #corners, ids, rejected_img_points = aruco.detectMarkers(gray, cv2.aruco_dict,parameters=parameters)
    #aruco.drawDetectedMarkers(frame, corners, ids)
    corners, ids, rejected = aruco.detectMarkers(frame, aruco_dict, parameters=parameters)
    R_list=[]

    if np.all(ids is not None):  # If there are markers found by detector
        for i in range(0, len(ids)):  # Iterate in markers

        # Estimate pose of each marker and return the values rvec and tvec---different from camera coefficients
            rvec, tvec, markerPoints = aruco.estimatePoseSingleMarkers(corners[i], 2.7, matrix_coefficients,
                                                                   distortion_coefficients)
            (rvec - tvec).any()  # get rid of that nasty numpy value array error
            #print(tvec)


            #aruco.drawDetectedMarkers(frame, corners)  # Draw A square around the markers
            aruco.drawDetectedMarkers(frame, corners, ids)
            cv2.drawFrameAxes(frame, matrix_coefficients, distortion_coefficients, rvec, tvec, 3)  # Draw Axis


            R, _ = cv2.Rodrigues(rvec)
            # convert (np.matrix(R).T) matrix to array using np.squeeze(np.asarray()) to get rid off the ValueError: shapes (1,3) and (1,3) not aligned
            R = np.squeeze(np.asarray(np.matrix(R).T))
            R_list.append(R[2])
            #print(len(R_list))


        # Display the resulting frame


    if len(R_list) == 2:


        print('##############')
        angle_radians = np.arccos(np.dot(R_list[0], R_list[1]))
        angle_degrees=angle_radians*180/np.pi
        print(angle_degrees)

#     aruco.drawDetectedMarkers(frame, corners, ids)
#     #return frame
#     if len(corners) > 0:
#         for i in range(0, len(ids)):
           
#             rvec, tvec, markerPoints = cv2.aruco.estimatePoseSingleMarkers(corners[i], 0.02, matrix_coefficients,
#                                                                        distortion_coefficients)
            
#             cv2.aruco.drawDetectedMarkers(frame, corners) 

#             cv2.drawFrameAxes(frame, matrix_coefficients, distortion_coefficients, rvec, tvec, 0.01)
#             #result_img = cv2.drawFrameAxes(dst1, mtx, dist, rvec[i, :, :], tvec[i, :, :],0.03)
    
    return frame

# store rz1 and rz2
    
     


    

aruco_type = "DICT_4X4_50"

arucoDict = cv2.aruco.Dictionary_get(ARUCO_DICT[aruco_type])

arucoParams = cv2.aruco.DetectorParameters_create()
#parameters = aruco.DetectorParameters_create()
#M = None
distortion_coefficients_path ='C:/Users/Raj/Desktop/Independent Study/calibrate/distortion_coefficients.npy'
calibration_matrix_path = 'C:/Users/Raj/Desktop/Independent Study/calibrate/new_calibration_matrix.npy'

k = np.load(calibration_matrix_path)
d = np.load(distortion_coefficients_path)

intrinsic_camera = k
distortion = d


cap = cv2.VideoCapture("http://192.168.1.90:8080/video")

cap.set(cv2.CAP_PROP_FRAME_WIDTH, 1280)
cap.set(cv2.CAP_PROP_FRAME_HEIGHT, 720)



while cap.isOpened():
    
    ret, img = cap.read()
    
    output = pose_estimation(img, ARUCO_DICT[aruco_type], intrinsic_camera, distortion)

    cv2.imshow('Estimated Pose', output)

    key = cv2.waitKey(1) & 0xFF
    if key == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()

In [ ]:
import cv2
import numpy as np
import time
import cv2.aruco as aruco

import time

In [ ]:
aruco_dict = aruco.Dictionary_get(aruco.DICT_4X4_50)

# Define the parameters for the marker detection
parameters = aruco.DetectorParameters_create()
M = None


# A required callback method that goes into the trackbar function.
def nothing(x):
    pass


In [ ]:
cap = cv2.VideoCapture("http://192.168.1.90:8080/video")

In [ ]:
while True:
    ret, frame = cap.read()
    corners, ids, rejected = aruco.detectMarkers(frame, aruco_dict, parameters=parameters)
    aruco.drawDetectedMarkers(frame, corners, ids)
    #corners, ids, rejected = aruco.detectMarkers(frame, aruco_
    cv2.imshow("im",frame)
    key = cv2.waitKey(1)
    if key == 27:
        break
cap.release()
cv2.destroyAllWindows()
    

In [ ]:
import numpy as np
import cv2.aruco as aruco
import sys
import time
import cv2

ARUCO_DICT = {
	"DICT_4X4_50": cv2.aruco.DICT_4X4_50,
	"DICT_4X4_100": cv2.aruco.DICT_4X4_100,
	"DICT_4X4_250": cv2.aruco.DICT_4X4_250,
	"DICT_4X4_1000": cv2.aruco.DICT_4X4_1000,
	"DICT_5X5_50": cv2.aruco.DICT_5X5_50,
	"DICT_5X5_100": cv2.aruco.DICT_5X5_100,
	"DICT_5X5_250": cv2.aruco.DICT_5X5_250,
	"DICT_5X5_1000": cv2.aruco.DICT_5X5_1000,
	"DICT_6X6_50": cv2.aruco.DICT_6X6_50,
	"DICT_6X6_100": cv2.aruco.DICT_6X6_100,
	"DICT_6X6_250": cv2.aruco.DICT_6X6_250,
	"DICT_6X6_1000": cv2.aruco.DICT_6X6_1000,
	"DICT_7X7_50": cv2.aruco.DICT_7X7_50,
	"DICT_7X7_100": cv2.aruco.DICT_7X7_100,
	"DICT_7X7_250": cv2.aruco.DICT_7X7_250,
	"DICT_7X7_1000": cv2.aruco.DICT_7X7_1000,
	"DICT_ARUCO_ORIGINAL": cv2.aruco.DICT_ARUCO_ORIGINAL,
	"DICT_APRILTAG_16h5": cv2.aruco.DICT_APRILTAG_16h5,
	"DICT_APRILTAG_25h9": cv2.aruco.DICT_APRILTAG_25h9,
	"DICT_APRILTAG_36h10": cv2.aruco.DICT_APRILTAG_36h10,
	"DICT_APRILTAG_36h11": cv2.aruco.DICT_APRILTAG_36h11
}

def pose_estimation(frame, aruco_dict_type, matrix_coefficients, distortion_coefficients):

    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    aruco_dict = aruco.Dictionary_get(aruco_dict_type)
    parameters = aruco.DetectorParameters_create()
    corners, ids, rejected = aruco.detectMarkers(frame, aruco_dict, parameters=parameters)
    R_list=[]
    a =0.0
    b =0.0
    
    #print(ids)

    if np.all(ids is not None):
        if 8 in ids:
            index_a = int(np.where(ids == 8)[0])
        else:
            
            index_a = -1  # Marker ID 7 not found
        if 6 in ids:
            index_b = int(np.where(ids == 6)[0])
        else:
            index_b = -1  # Marker ID 8 not found

        rvec_a, tvec_a, markerPoints_a = aruco.estimatePoseSingleMarkers(corners[index_a], 2.7, matrix_coefficients,distortion_coefficients)
        (rvec_a - tvec_a).any()  # get rid of that nasty numpy value array error
        rvec_b, tvec_b, markerPoints_b = aruco.estimatePoseSingleMarkers(corners[index_b], 2.7, matrix_coefficients,distortion_coefficients)
        (rvec_b - tvec_b).any()  # get rid of that nasty numpy value array error
        xa = tvec_a[0][0][0]
        xb = tvec_b[0][0][0]
        ya = tvec_a[0][0][1]
        yb = tvec_b[0][0][1]
        #print(tvec_a,tvec_b)
        print(f"distance:{xb-xa} and {ya-yb}")
        aruco.drawDetectedMarkers(frame, corners)  # Draw A square around the markers
        aruco.drawDetectedMarkers(frame, corners, ids)
        cv2.drawFrameAxes(frame, matrix_coefficients, distortion_coefficients, rvec_a, tvec_a, 2.7)  # Draw Axis
        cv2.drawFrameAxes(frame, matrix_coefficients, distortion_coefficients, rvec_b, tvec_b, 2.7)  # Draw Axis
    return frame

aruco_type = "DICT_4X4_50"

arucoDict = cv2.aruco.Dictionary_get(ARUCO_DICT[aruco_type])

arucoParams = cv2.aruco.DetectorParameters_create()
distortion_coefficients_path ='C:/Users/Raj/Desktop/Independent Study/calibrate/distortion_coefficients.npy'
calibration_matrix_path = 'C:/Users/Raj/Desktop/Independent Study/calibrate/new_calibration_matrix.npy'

k = np.load(calibration_matrix_path)
d = np.load(distortion_coefficients_path)

intrinsic_camera = k
distortion = d


cap = cv2.VideoCapture("http://192.168.1.90:8080/video")
while cap.isOpened():
    
    ret, img = cap.read()
    
    output = pose_estimation(img, ARUCO_DICT[aruco_type], intrinsic_camera, distortion)

    cv2.imshow('Estimated Pose', output)

    key = cv2.waitKey(1) & 0xFF
    if key == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()

In [171]:
cv2.destroyAllWindows()

In [ ]:
import numpy as np
import cv2.aruco as aruco
import sys
import time
import cv2

distortion_coefficients_path ='C:/Users/Raj/Desktop/Independent Study/calibrate/distortion_coefficients.npy'
calibration_matrix_path = 'C:/Users/Raj/Desktop/Independent Study/calibrate/new_calibration_matrix.npy'
matrix_coefficients = np.load(calibration_matrix_path)
distortion_coefficients = np.load(distortion_coefficients_path)

nb_markers=2
cap = cv2.VideoCapture("http://192.168.1.90:8080/video")
def track(matrix_coefficients, distortion_coefficients):
    while True:
        ret, frame = cap.read()
        gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY) 
        aruco_dict = aruco.Dictionary_get(aruco.DICT_4X4_50)
        parameters = aruco.DetectorParameters_create()
        #corners, ids, rejected_img_points = aruco.detectMarkers(gray,aruco_dict,parameters=parameters,cameraMatrix=matrix_coefficients,distCoeff=distortion_coefficients)    
        corners, ids, rejected = aruco.detectMarkers(gray, aruco_dict, parameters=parameters)
        R_list=[]
        if np.all(ids is not None): 
            for i in range(0, len(ids)): 
                rvec, tvec, markerPoints = aruco.estimatePoseSingleMarkers(corners[i], 3, matrix_coefficients,distortion_coefficients)
                (rvec - tvec).any() 
                aruco.drawDetectedMarkers(frame, corners)
                #aruco.drawAxis(frame, matrix_coefficients, distortion_coefficients, rvec, tvec, 0.01)
                cv2.drawFrameAxes(frame, matrix_coefficients, distortion_coefficients, rvec, tvec, 3)
                R, _ = cv2.Rodrigues(rvec)
                R = np.squeeze(np.asarray(np.matrix(R).T))
                R_list.append(R[2])
        if len(R_list) == 2:
            print('##############')
            angle_radians = np.arccos(np.dot(R_list[0], R_list[1]))
            angle_degrees=angle_radians*180/np.pi
            print(angle_degrees)
        cv2.imshow('frame', frame)
        key = cv2.waitKey(1) & 0xFF
        if key == ord('q'):
            ("Ok")
            break
track(matrix_coefficients, distortion_coefficients)

In [ ]:
cv2.destroyAllWindows()

In [ ]:
import numpy as np
import cv2.aruco as aruco
import sys
import time
import cv2
import math

distortion_coefficients_path ='C:/Users/Raj/Desktop/Independent Study/calibrate/distortion_coefficients.npy'
calibration_matrix_path = 'C:/Users/Raj/Desktop/Independent Study/calibrate/new_calibration_matrix.npy'
matrix_coefficients = np.load(calibration_matrix_path)
distortion_coefficients = np.load(distortion_coefficients_path)
nb_markers=2
#cap = cv2.VideoCapture("http://192.168.1.90:8080/video")
cap = cv2.VideoCapture("http://10.84.88.194:8080/video")
#10.84.88.194

while True:
    ret, frame = cap.read()
    frame = cv2.resize(frame, (480 * 2, 270 * 2))
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY) 
    aruco_dict = aruco.Dictionary_get(aruco.DICT_4X4_50)
    parameters = aruco.DetectorParameters_create()
    #corners, ids, rejected_img_points = aruco.detectMarkers(gray,aruco_dict,parameters=parameters,cameraMatrix=matrix_coefficients,distCoeff=distortion_coefficients)    
    corners, ids, rejected = aruco.detectMarkers(gray, aruco_dict, parameters=parameters)
    print(ids)
    if np.all(ids is not None):
        
        
        if 8 in ids:
            index_a = int(np.where(ids == 8)[0])
        else:
            index_a = -1  # Marker ID 7 not found
        if 7 in ids:
            index_b = int(np.where(ids == 7)[0])
        else:
            index_b = -1  # Marker ID 8 not foundd
        rvec_6, tvec_6, markerPoints = cv2.aruco.estimatePoseSingleMarkers(corners[index_b], 3, matrix_coefficients, distortion_coefficients)
        rvec_7, tvec_7, markerPoints_7 = cv2.aruco.estimatePoseSingleMarkers(corners[index_a], 3, matrix_coefficients, distortion_coefficients)
        #print(tvec_3)
        #print(tvec_7)
        #R1, _ = cv2.Rodrigues(rvec_3)
        #R2, _ = cv2.Rodrigues(rvec_7)
        rmat_3, jacobian_3 = cv2.Rodrigues(rvec_6)
        isRotationMatrix(rmat_3)
        a_6 = rotationMatrixToEulerAngles(rmat_3)
        #print(a_3[2])
        rmat_7, jacobian_7 = cv2.Rodrigues(rvec_7)
        isRotationMatrix(rmat_7)
        a_7 = rotationMatrixToEulerAngles(rmat_7)
        #print(a_7[2])
        #angle_radians = np.arccos(np.dot(a_3[2],  a_7[2]))
        #print(f"angle:{(360.0 -abs(a_7[2] - a_6[2]))} and {(a_6[2] - a_7[2])}")
    # Extract the third columns of the rotation matrices
#         rz1 = R1[:, 2]
#         rz2 = R2[:, 2]
#         #rz1  = rvec_3[0][0][2]
#         #rz2 = rvec_7[0][0][2]
#         angle_radians = np.arccos(np.dot(rz1, rz2))
#         angle_degrees=angle_radians*180/np.pi
#         print("angle: ",angle_degrees)
        a = tvec_6[0][0][0]
        b = tvec_7[0][0][0]
        a_ = tvec_6[0][0][1]
        b_ = tvec_7[0][0][1]
        print(f"distance:{(a_-b_)} and{(a-b)} ")
        
#         theta_deg = float(input("Enter the rotation angle of the robot in degrees: "))
#         x_obj_world = float(input("Enter the x-coordinate of the object in the world frame: "))
#         y_obj_world = float(input("Enter the y-coordinate of the object in the world frame: "))
#         x_robot_world = float(input("Enter the x-coordinate of the robot in the world frame: "))
#         y_robot_world = float(input("Enter the y-coordinate of the robot in the world frame: "))
#         theta_rad = math.radians(theta_deg)

#         # Calculate relative position in the world frame
#         x_rel_world = x_obj_world - x_robot_world
#         y_rel_world = y_obj_world - y_robot_world

#         # Apply reverse rotation transformation to obtain coordinates in the robot's frame
#         x_rel_robot = x_rel_world * math.cos(theta_rad) + y_rel_world * math.sin(theta_rad)
#         y_rel_robot = -x_rel_world * math.sin(theta_rad) + y_rel_world * math.cos(theta_rad)

        # Optionally, apply translation if needed
#         x_obj_robot = x_rel_robot
#         y_obj_robot = y_rel_robot
        #print("angle: ",rz1 -rz2)
    
        aruco.drawDetectedMarkers(frame, corners)  # Draw A square around the markers
        aruco.drawDetectedMarkers(frame, corners, ids)
        cv2.drawFrameAxes(frame, matrix_coefficients, distortion_coefficients, rvec_6, tvec_6, 30)  # Draw Axis
        cv2.drawFrameAxes(frame, matrix_coefficients, distortion_coefficients, rvec_7, tvec_7, 30)  # Draw Axis
    cv2.imshow('frame', frame)
#     #print(frame.shape)
    key = cv2.waitKey(1) & 0xFF
    if key == ord('q'):
        ("Ok")
        break
cv2.destroyAllWindows()

[[8]
 [7]]
distance:-11.428005166557796 and146.43894712577486 
[[8]
 [7]]
distance:-11.428005166557796 and146.43894712577486 
[[8]
 [7]]
distance:-11.428005166557796 and146.43894712577486 
[[8]
 [7]]
distance:-11.428005166557796 and146.43894712577486 
[[8]
 [7]]
distance:-11.428005166557796 and146.43894712577486 
[[8]
 [7]]
distance:-11.428005166557796 and146.43894712577486 
[[8]
 [7]]
distance:-11.428005166557796 and146.43894712577486 
[[8]
 [7]]
distance:-11.428005166557796 and146.43894712577486 
[[8]
 [7]]
distance:-11.428005166557796 and146.43894712577486 
[[8]
 [7]]
distance:-11.428005166557796 and146.43894712577486 
[[8]
 [7]]
distance:-11.428005166557796 and146.43894712577486 
[[8]
 [7]]
distance:-11.428005166557796 and146.43894712577486 
[[8]
 [7]]
distance:-11.428005166557796 and146.43894712577486 
[[8]
 [7]]
distance:-11.428005166557796 and146.43894712577486 
[[8]
 [7]]
distance:-11.428005166557796 and146.43894712577486 
[[8]
 [7]]
distance:-11.428005166557796 and146.43894712

[[8]
 [7]]
distance:-11.428005166557796 and146.43894712577486 
[[8]
 [7]]
distance:-11.428005166557796 and146.43894712577486 
[[8]
 [7]]
distance:-11.428005166557796 and146.43894712577486 
[[8]
 [7]]
distance:-11.428005166557796 and146.43894712577486 
[[8]
 [7]]
distance:-11.428005166557796 and146.43894712577486 
[[8]
 [7]]
distance:-11.428005166557796 and146.43894712577486 
[[8]
 [7]]
distance:-11.428005166557796 and146.43894712577486 
[[8]
 [7]]
distance:-11.428005166557796 and146.43894712577486 
[[8]
 [7]]
distance:-11.428005166557796 and146.43894712577486 
[[8]
 [7]]
distance:-11.428005166557796 and146.43894712577486 
[[8]
 [7]]
distance:-11.428005166557796 and146.43894712577486 
[[8]
 [7]]
distance:-11.428005166557796 and146.43894712577486 
[[8]
 [7]]
distance:-11.428005166557796 and146.43894712577486 
[[8]
 [7]]
distance:-11.428005166557796 and146.43894712577486 
[[8]
 [7]]
distance:-11.428005166557796 and146.43894712577486 
[[8]
 [7]]
distance:-11.428005166557796 and146.43894712

[[8]
 [7]]
distance:-11.428005166557796 and146.43894712577486 
[[8]
 [7]]
distance:-11.428005166557796 and146.43894712577486 
[[8]
 [7]]
distance:-11.428005166557796 and146.43894712577486 
[[8]
 [7]]
distance:-11.428005166557796 and146.43894712577486 
[[8]
 [7]]
distance:-11.428005166557796 and146.43894712577486 
[[8]
 [7]]
distance:-11.428005166557796 and146.43894712577486 
[[8]
 [7]]
distance:-11.428005166557796 and146.43894712577486 
[[8]
 [7]]
distance:-11.428005166557796 and146.43894712577486 
[[8]
 [7]]
distance:-11.428005166557796 and146.43894712577486 
[[8]
 [7]]
distance:-11.428005166557796 and146.43894712577486 
[[8]
 [7]]
distance:-11.428005166557796 and146.43894712577486 
[[8]
 [7]]
distance:-11.428005166557796 and146.43894712577486 
[[8]
 [7]]
distance:-11.428005166557796 and146.43894712577486 
[[8]
 [7]]
distance:-11.428005166557796 and146.43894712577486 
[[8]
 [7]]
distance:-11.428005166557796 and146.43894712577486 
[[8]
 [7]]
distance:-11.428005166557796 and146.43894712

[[7]
 [8]]
distance:72.49993654403721 and85.33786757718389 
[[7]
 [8]]
distance:72.49993654403721 and85.33786757718389 
[[7]
 [8]]
distance:72.49993654403721 and85.33786757718389 
[[7]
 [8]]
distance:72.49993654403721 and85.33786757718389 
[[7]
 [8]]
distance:72.49993654403721 and85.33786757718389 
[[7]
 [8]]
distance:72.49993654403721 and85.33786757718389 
[[7]
 [8]]
distance:72.49993654403721 and85.33786757718389 
[[7]
 [8]]
distance:72.49993654403721 and85.33786757718389 
[[7]
 [8]]
distance:72.49993654403721 and85.33786757718389 
[[7]
 [8]]
distance:72.49993654403721 and85.33786757718389 
[[7]
 [8]]
distance:72.49993654403721 and85.33786757718389 
[[7]
 [8]]
distance:72.49993654403721 and85.33786757718389 
[[7]
 [8]]
distance:72.49993654403721 and85.33786757718389 
[[7]
 [8]]
distance:72.49993654403721 and85.33786757718389 
[[7]
 [8]]
distance:72.49993654403721 and85.33786757718389 
[[7]
 [8]]
distance:72.49993654403721 and85.33786757718389 
[[7]
 [8]]
distance:72.49993654403721 an

[[7]
 [8]]
distance:73.95061084532716 and86.83298525667749 
[[7]
 [8]]
distance:73.95061084532716 and86.83298525667749 
[[8]
 [7]]
distance:73.95061084532716 and86.83298525667749 
[[7]
 [8]]
distance:73.95061084532716 and86.83298525667749 
[[8]
 [7]]
distance:73.95061084532716 and86.83298525667749 
[[7]
 [8]]
distance:73.95061084532716 and86.83298525667749 
[[7]
 [8]]
distance:73.27988744387375 and85.79430948753458 
[[7]
 [8]]
distance:73.20801120170535 and86.361695722153 
[[7]
 [8]]
distance:73.95061084532716 and86.83298525667749 
[[7]
 [8]]
distance:73.95061084532716 and86.83298525667749 
[[7]
 [8]]
distance:73.95061084532716 and86.83298525667749 
[[7]
 [8]]
distance:73.95061084532716 and86.83298525667749 
[[7]
 [8]]
distance:73.95061084532716 and86.83298525667749 
[[7]
 [8]]
distance:73.95061084532716 and86.83298525667749 
[[7]
 [8]]
distance:73.95061084532716 and86.83298525667749 
[[7]
 [8]]
distance:73.95061084532716 and86.83298525667749 
[[7]
 [8]]
distance:73.95061084532716 and8

[[7]
 [8]]
distance:72.49993654403721 and85.33786757718389 
[[7]
 [8]]
distance:72.49993654403721 and85.33786757718389 
[[7]
 [8]]
distance:72.49993654403721 and85.33786757718389 
[[7]
 [8]]
distance:72.49993654403721 and85.33786757718389 
[[7]
 [8]]
distance:72.49993654403721 and85.33786757718389 
[[7]
 [8]]
distance:72.49993654403721 and85.33786757718389 
[[7]
 [8]]
distance:72.49993654403721 and85.33786757718389 
[[7]
 [8]]
distance:72.49993654403721 and85.33786757718389 
[[7]
 [8]]
distance:73.27988744387375 and85.79430948753458 
[[7]
 [8]]
distance:73.27988744387375 and85.79430948753458 
[[7]
 [8]]
distance:72.49993654403721 and85.33786757718389 
[[7]
 [8]]
distance:72.49993654403721 and85.33786757718389 
[[7]
 [8]]
distance:72.49993654403721 and85.33786757718389 
[[7]
 [8]]
distance:72.49993654403721 and85.33786757718389 
[[7]
 [8]]
distance:73.27988744387375 and85.79430948753458 
[[7]
 [8]]
distance:72.49993654403721 and85.33786757718389 
[[7]
 [8]]
distance:72.49993654403721 an

[[7]
 [8]]
distance:72.49993654403721 and85.33786757718389 
[[7]
 [8]]
distance:73.27988744387375 and85.79430948753458 
[[7]
 [8]]
distance:73.27988744387375 and85.79430948753458 
[[7]
 [8]]
distance:73.27988744387375 and85.79430948753458 
[[7]
 [8]]
distance:73.27988744387375 and85.79430948753458 
[[7]
 [8]]
distance:73.27988744387375 and85.79430948753458 
[[7]
 [8]]
distance:72.49993654403721 and85.33786757718389 
[[7]
 [8]]
distance:73.27988744387375 and85.79430948753458 
[[7]
 [8]]
distance:73.27988744387375 and85.79430948753458 
[[7]
 [8]]
distance:73.27988744387375 and85.79430948753458 
[[7]
 [8]]
distance:73.27988744387375 and85.79430948753458 
[[7]
 [8]]
distance:73.27988744387375 and85.79430948753458 
[[7]
 [8]]
distance:73.27988744387375 and85.79430948753458 
[[7]
 [8]]
distance:73.27988744387375 and85.79430948753458 
[[7]
 [8]]
distance:73.27988744387375 and85.79430948753458 
[[7]
 [8]]
distance:73.95061084532716 and86.83298525667749 
[[7]
 [8]]
distance:73.95061084532716 an

[[7]
 [8]]
distance:73.27988744387375 and85.79430948753458 
[[7]
 [8]]
distance:73.95061084532716 and86.83298525667749 
[[7]
 [8]]
distance:73.95061084532716 and86.83298525667749 
[[7]
 [8]]
distance:73.95061084532716 and86.83298525667749 
[[7]
 [8]]
distance:73.27988744387375 and85.79430948753458 
[[7]
 [8]]
distance:73.95061084532716 and86.83298525667749 
[[7]
 [8]]
distance:73.27988744387375 and85.79430948753458 
[[7]
 [8]]
distance:73.95061084532716 and86.83298525667749 
[[7]
 [8]]
distance:73.95061084532716 and86.83298525667749 
[[7]
 [8]]
distance:73.95061084532716 and86.83298525667749 
[[7]
 [8]]
distance:73.95061084532716 and86.83298525667749 
[[7]
 [8]]
distance:73.95061084532716 and86.83298525667749 
[[7]
 [8]]
distance:73.95061084532716 and86.83298525667749 
[[7]
 [8]]
distance:73.95061084532716 and86.83298525667749 
[[7]
 [8]]
distance:73.95061084532716 and86.83298525667749 
[[7]
 [8]]
distance:73.95061084532716 and86.83298525667749 
[[7]
 [8]]
distance:73.95061084532716 an

[[7]
 [8]]
distance:72.49993654403721 and85.33786757718389 
[[7]
 [8]]
distance:72.49993654403721 and85.33786757718389 
[[7]
 [8]]
distance:72.49993654403721 and85.33786757718389 
[[7]
 [8]]
distance:72.49993654403721 and85.33786757718389 
[[7]
 [8]]
distance:72.49993654403721 and85.33786757718389 
[[7]
 [8]]
distance:72.49993654403721 and85.33786757718389 
[[7]
 [8]]
distance:72.49993654403721 and85.33786757718389 
[[7]
 [8]]
distance:72.49993654403721 and85.33786757718389 
[[7]
 [8]]
distance:72.49993654403721 and85.33786757718389 
[[7]
 [8]]
distance:72.49993654403721 and85.33786757718389 
[[7]
 [8]]
distance:72.49993654403721 and85.33786757718389 
[[7]
 [8]]
distance:72.49993654403721 and85.33786757718389 
[[7]
 [8]]
distance:72.49993654403721 and85.33786757718389 
[[7]
 [8]]
distance:72.49993654403721 and85.33786757718389 
[[7]
 [8]]
distance:72.49993654403721 and85.33786757718389 
[[7]
 [8]]
distance:72.49993654403721 and85.33786757718389 


In [ ]:
cv2.destroyAllWindows()

In [2]:
def isRotationMatrix(R) : 
    Rt = np.transpose(R) 
    shouldBeIdentity = np.dot(Rt, R) 
    I = np.identity(3, dtype = R.dtype) 
    n = np.linalg.norm(I - shouldBeIdentity) 
    return n < 1e-6

In [3]:
def rotationMatrixToEulerAngles(R): 
    assert(isRotationMatrix(R))
    sy = math.sqrt(R[0,0] * R[0,0] + R[1,0] * R[1,0])

    singular = sy < 1e-6

    if not singular :
        x = math.atan2(R[2,1] , R[2,2])
        y = math.atan2(-R[2,0], sy)
        z = math.atan2(R[1,0], R[0,0])
        # z = math.atan2(R[0,1], -R[1,1])
    else:
        x = math.atan2(-R[1,2], R[1,1])
        y = math.atan2(-R[2,0], sy)
        z = 0

    return np.array([x, y, z]) * (180/np.pi) # move 

In [4]:
from uarm.wrapper import SwiftAPI
#swift = SwiftAPI()
import cv2, queue, threading, time
import cv2
import numpy as np
import time
import cv2.aruco as aruco
from uarm.wrapper import SwiftAPI
import time
import queue, threading, time
import math

aruco_dict = aruco.Dictionary_get(aruco.DICT_4X4_50)
parameters = aruco.DetectorParameters_create()
distortion_coefficients_path ='C:/Users/Raj/Desktop/Independent Study/calibrate/distortion_coefficients.npy'
calibration_matrix_path = 'C:/Users/Raj/Desktop/Independent Study/calibrate/new_calibration_matrix.npy'

matrix_coefficients = np.load(calibration_matrix_path)
distortion_coefficients = np.load(distortion_coefficients_path)

M = None
wname = "Trackbars"
cv2.namedWindow(wname)
wname1 = "image"
cv2.namedWindow(wname1)

l_h = 0
l_s = 0
l_v = 0
u_h = 179
u_s = 255
u_v = 255
hsv = None

def move_robot(u, v):
    x = round(u, 2)
    y = 88+round(v, 2)
    swift.set_position(x=x, y=y, z=100, speed=10000)
    time.sleep(1.0)
    swift.set_position(x=x, y=y, z=40, speed=10000)
    time.sleep(1.0)
    swift.set_pump(on=True)
    time.sleep(2)
    swift.set_position(x=x, y=x, z=100, speed=10000)
    time.sleep(1)
    swift.set_position(x=0, y=-100, z=100, speed=10000)
    time.sleep(1.0)
    swift.set_position(x=0, y=-100, z=70, speed=10000)
    time.sleep(1.0)
    swift.set_pump(on=False)
    time.sleep(1.0)
    swift.set_position(x=0, y=0, z=100, speed=10000)

class VideoCapture:
    def __init__(self, name):
        self.cap = cv2.VideoCapture(name)
        self.q = queue.Queue()
        t = threading.Thread(target=self._reader)
        t.daemon = True
        t.start()

    def _reader(self):
        while True:
            ret, frame = self.cap.read()
            if not ret:
                break
            if not self.q.empty():
                try:
                    self.q.get_nowait()
                except queue.Empty:
                    pass
            self.q.put(frame)

    def read(self):
        return self.q.get()
    def release(self):
        return self.cap.release()

def isRotationMatrix(R) : 
    Rt = np.transpose(R) 
    shouldBeIdentity = np.dot(Rt, R) 
    I = np.identity(3, dtype = R.dtype) 
    n = np.linalg.norm(I - shouldBeIdentity) 
    return n < 1e-6

def rotationMatrixToEulerAngles(R): 
    assert(isRotationMatrix(R))
    sy = math.sqrt(R[0,0] * R[0,0] + R[1,0] * R[1,0])

    singular = sy < 1e-6

    if not singular :
        x = math.atan2(R[2,1] , R[2,2])
        y = math.atan2(-R[2,0], sy)
        z = math.atan2(R[1,0], R[0,0])
        # z = math.atan2(R[0,1], -R[1,1])
    else:
        x = math.atan2(-R[1,2], R[1,1])
        y = math.atan2(-R[2,0], sy)
        z = 0

    return np.array([x, y, z]) * (180/np.pi) # move 

def pixel_mm(u,v):
    sccale_factor = (12*25.4)/500
    x_cord = u*sccale_factor
    y_coord = v *sccale_factor
    return x_cord,y_coord


def onclick(event, x, y, flags, param):
    global u_s, u_v, u_h, l_h, l_s, l_v, hsv
    if event == cv2.EVENT_LBUTTONDOWN:
        print("x: %d, y: %d" % (x, y))
        l_h = max(hsv[y, x][0] - 10, 0)
        l_s = max(hsv[y, x][1] - 40, 0)
        l_v = max(hsv[y, x][2] - 40, 0)
        u_h = min(hsv[y, x][0] + 10, 179)
        u_s = min(hsv[y, x][1] + 40, 255)
        u_v = min(hsv[y, x][2] + 40, 255)
    

rectangle = None
cv2.setMouseCallback(wname1, onclick)

#swift.connect()
#cap = VideoCapture("http://10.84.18.188:8080/video")
#cap = VideoCapture("http://192.168.1.90:8080/video")
cap = VideoCapture("http://10.84.88.194:8080/video")
while True:
    frame = cap.read()
    frame = cv2.resize(frame, (480 * 2, 270 * 2))
    frame_new = frame
    corners, ids, rejected = aruco.detectMarkers(frame, aruco_dict, parameters=parameters)
    if np.all(ids is not None):
        if 7 in ids:
            index_a = int(np.where(ids == 7)[0])
        else:
            index_a = -1  # Marker ID 7 not found
        if 8 in ids:
            index_b = int(np.where(ids == 8)[0])
        else:
            index_b = -1  # Marker ID 8 not found

        rvec_a, tvec_a, markerPoints_a = aruco.estimatePoseSingleMarkers(corners[index_a], 3, matrix_coefficients,distortion_coefficients)
        (rvec_a - tvec_a).any()  # get rid of that nasty numpy value array error
        rvec_b, tvec_b, markerPoints_b = aruco.estimatePoseSingleMarkers(corners[index_b], 3, matrix_coefficients,distortion_coefficients)
        (rvec_b - tvec_b).any()  # get rid of that nasty numpy value array error
        rmat_3, jacobian_3 = cv2.Rodrigues(rvec_b)
        isRotationMatrix(rmat_3)
        a_3 = rotationMatrixToEulerAngles(rmat_3)
        #print(a_3[2])
        rmat_7, jacobian_7 = cv2.Rodrigues(rvec_a)
        isRotationMatrix(rmat_7)
        a_7 = rotationMatrixToEulerAngles(rmat_7)
        #print(f"angle:{(360.0 -abs(a_7[2] - a_3[2]))} and {(a_3[2] - a_7[2])}")
        a = tvec_a[0][0][0]
        b = tvec_b[0][0][0]
        a_ = tvec_a[0][0][1]
        b_ = tvec_b[0][0][1]
        ya = (b-a)
        xa =(a_-b_)
        
        print(f"distance:{ya} and {xa}")
        aruco.drawDetectedMarkers(frame, corners)  # Draw A square around the markers
        aruco.drawDetectedMarkers(frame, corners, ids)
        cv2.drawFrameAxes(frame, matrix_coefficients, distortion_coefficients, rvec_a, tvec_a, 3)  # Draw Axis
        cv2.drawFrameAxes(frame, matrix_coefficients, distortion_coefficients, rvec_b, tvec_b, 3)  # Draw Axis
    
    #rvec, tvec, markerPoints = aruco.estimatePoseSingleMarkers(corners[i], 3, matrix_coefficients,distortion_coefficients)
    output_coords = np.float32([[0, 0], [500, 0], [500, 300], [0, 300]])
    if len(corners) == 4 and M is None:
        src_pts = np.float32([corners[np.where(ids == 3)[0][0]][0][0], corners[np.where(ids == 2)[0][0]][0][1],
                          corners[np.where(ids == 0)[0][0]][0][2], corners[np.where(ids == 1)[0][0]][0][3]])
        dst_pts = np.float32([[0, 0], [0, 500], [500, 500], [500, 0]])
        M = cv2.getPerspectiveTransform(src_pts, dst_pts)
    if M is not None:
        warped = cv2.warpPerspective(frame, M, (500, 500))
        frame = warped
    aruco.drawDetectedMarkers(frame, corners, ids)
    hsv = cv2.cvtColor(frame, cv2.COLOR_BGR2HSV)
    lower_range = np.array([l_h, l_s, l_v])
    upper_range = np.array([u_h, u_s, u_v])
    mask = cv2.inRange(hsv, lower_range, upper_range)
    kernel = np.ones((5, 5), np.uint8)
    mask = cv2.morphologyEx(mask, cv2.MORPH_OPEN, kernel)
    contours, hierarchy = cv2.findContours(mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    ball_count = 0
    cordinates = []
    for contour in contours:
        area = cv2.contourArea(contour)
        if area > 200 and area < 10000:
            (x, y), radius = cv2.minEnclosingCircle(contour)
            center = (int(x), int(y))
            radius = int(radius)
            moments = cv2.moments(contour)
            cv2.circle(frame, center, radius, (0, 255, 0), 2)
            centroid_x = int(moments['m10'] / moments['m00'])
            centroid_y = int(moments['m01'] / moments['m00'])
            cv2.circle(frame, (centroid_x, centroid_y), 5, (0, 255, 255), -1)
            ball_count += 1
            cordinates.append(center)
            if cordinates is not None:
                for i in cordinates:
                    u, v = i
                    x, y = pixel_mm(u, v)
                    print(x,y)
                    x = x-xa
                    y =y 
                    print("length:", len(cordinates))
                    print("moving to:", (x, y))
                    move_robot(x,y)
                cordinates = []

    cv2.imshow('Trackbars', mask)
    cv2.imshow("test",frame_new)
    frame = cv2.putText(frame, "X", (250, 250), cv2.FONT_HERSHEY_SIMPLEX, 1, (255, 255, 0), 3)
    cv2.imshow(wname1, frame)
    if chr(cv2.waitKey(1)&255) == 'q':
        break

cv2.destroyAllWindows()
cap.release()
swift.reset()


distance:-4.2444272161114895 and 2.435879207443481
distance:-4.2444272161114895 and 2.435879207443481
distance:-4.2444272161114895 and 2.435879207443481
distance:-4.2444272161114895 and 2.435879207443481
distance:-3.8837640789297616 and 2.2336620640700744
distance:-4.222884973621053 and 2.4283542927366923
distance:-4.222884973621053 and 2.4283542927366923
distance:-4.222884973621053 and 2.4283542927366923
distance:-4.222884973621053 and 2.4283542927366923
distance:-4.222884973621053 and 2.4283542927366923
distance:-4.2444272161114895 and 2.435879207443481
distance:-3.8837640789297616 and 2.2336620640700744
distance:-3.8837640789297616 and 2.2336620640700744
distance:-3.8837640789297616 and 2.2336620640700744
distance:-3.862221836439325 and 2.2261371493632858
distance:-3.8837640789297616 and 2.2336620640700744
distance:-3.8837640789297616 and 2.2336620640700744
distance:-3.8837640789297616 and 2.2336620640700744
distance:-3.8837640789297616 and 2.2336620640700744
distance:-3.22439100978

distance:-3.8837640789297616 and 2.2336620640700744
distance:-3.8837640789297616 and 2.2336620640700744
distance:-3.8837640789297616 and 2.2336620640700744
distance:-3.8837640789297616 and 2.2336620640700744
distance:-3.8837640789297616 and 2.2336620640700744
distance:-4.2444272161114895 and 2.435879207443481
distance:-4.2444272161114895 and 2.435879207443481
distance:-4.222884973621053 and 2.4283542927366923
distance:-4.222884973621053 and 2.4283542927366923
distance:-4.222884973621053 and 2.4283542927366923
distance:-4.2444272161114895 and 2.435879207443481
distance:-4.222884973621053 and 2.4283542927366923
distance:-4.2444272161114895 and 2.435879207443481
distance:-4.2444272161114895 and 2.435879207443481
distance:-4.2444272161114895 and 2.435879207443481
distance:-4.2444272161114895 and 2.435879207443481
distance:-4.2444272161114895 and 2.435879207443481
distance:-4.2444272161114895 and 2.435879207443481
distance:-4.2444272161114895 and 2.435879207443481
distance:-4.24442721611148

distance:-3.5997703578486373 and 2.1113814503726758
distance:-3.5997703578486373 and 2.1113814503726758
distance:-2.9091167990600546 and 1.6492353226450476
distance:-3.5997703578486373 and 2.1113814503726758
distance:-3.2844961471214127 and 1.8927471474569764
distance:-3.5997703578486373 and 2.1113814503726758
distance:-3.2844961471214127 and 1.8927471474569764
distance:-3.5997703578486373 and 2.1113814503726758
distance:-3.5997703578486373 and 2.1113814503726758
distance:-4.258484124649286 and 2.4867649215601553
distance:-3.5997703578486373 and 2.1113814503726758
distance:-3.8837640789297616 and 2.2336620640700744
distance:-3.5997703578486373 and 2.1113814503726758
distance:-3.5997703578486373 and 2.1113814503726758
distance:-3.5997703578486373 and 2.1113814503726758
distance:-3.5997703578486373 and 2.1113814503726758
distance:-3.5997703578486373 and 2.1113814503726758
distance:-3.5997703578486373 and 2.1113814503726758
distance:-3.5997703578486373 and 2.1113814503726758
distance:-3.2

distance:-3.2844961471214127 and 1.8927471474569764
distance:-3.2844961471214127 and 1.8927471474569764
distance:-3.2844961471214127 and 1.8927471474569764
distance:-3.2844961471214127 and 1.8927471474569764
distance:-3.2844961471214127 and 1.8927471474569764
distance:-4.258484124649286 and 2.4867649215601553
distance:-4.258484124649286 and 2.4867649215601553
distance:-4.258484124649286 and 2.4867649215601553
distance:-3.2844961471214127 and 1.8927471474569764
distance:-3.943209913922061 and 2.268130618644456
distance:-3.2844961471214127 and 1.8927471474569764
distance:-3.943209913922061 and 2.268130618644456
distance:-3.943209913922061 and 2.268130618644456
distance:-3.943209913922061 and 2.268130618644456
distance:-3.2844961471214127 and 1.8927471474569764
distance:-3.2844961471214127 and 1.8927471474569764
distance:-3.2844961471214127 and 1.8927471474569764
distance:-3.2844961471214127 and 1.8927471474569764
distance:-3.2844961471214127 and 1.8927471474569764
distance:-3.28449614712

distance:-3.2844961471214127 and 1.8927471474569764
distance:-3.2844961471214127 and 1.8927471474569764
distance:-3.2844961471214127 and 1.8927471474569764
distance:-3.2844961471214127 and 1.8927471474569764
distance:-3.2844961471214127 and 1.8927471474569764
distance:-3.2844961471214127 and 1.8927471474569764
distance:-3.2844961471214127 and 1.8927471474569764
distance:-3.2844961471214127 and 1.8927471474569764
distance:-3.2844961471214127 and 1.8927471474569764
distance:-3.2844961471214127 and 1.8927471474569764
distance:-3.2844961471214127 and 1.8927471474569764
distance:-3.2844961471214127 and 1.8927471474569764
distance:-3.2844961471214127 and 1.8927471474569764
distance:-3.2844961471214127 and 1.8927471474569764
distance:-3.2844961471214127 and 1.8927471474569764
distance:-3.2844961471214127 and 1.8927471474569764
distance:-3.2844961471214127 and 1.8927471474569764
distance:-3.2844961471214127 and 1.8927471474569764
distance:-3.2844961471214127 and 1.8927471474569764
distance:-3.

distance:-3.2844961471214127 and 1.8927471474569764
distance:-3.2844961471214127 and 1.8927471474569764
distance:-3.2844961471214127 and 1.8927471474569764
distance:-3.2844961471214127 and 1.8927471474569764
distance:-3.2844961471214127 and 1.8927471474569764
distance:-3.2844961471214127 and 1.8927471474569764
distance:-3.2844961471214127 and 1.8927471474569764
distance:-3.2844961471214127 and 1.8927471474569764
distance:-3.2844961471214127 and 1.8927471474569764
distance:-3.2844961471214127 and 1.8927471474569764
distance:-3.2844961471214127 and 1.8927471474569764
distance:-3.2844961471214127 and 1.8927471474569764
distance:-3.2844961471214127 and 1.8927471474569764
distance:-3.2844961471214127 and 1.8927471474569764
distance:-3.2844961471214127 and 1.8927471474569764
distance:-3.2844961471214127 and 1.8927471474569764
distance:-3.2844961471214127 and 1.8927471474569764
distance:-3.2844961471214127 and 1.8927471474569764
distance:-3.2844961471214127 and 1.8927471474569764
distance:-3.

distance:-3.2844961471214127 and 1.8927471474569764
distance:-3.2844961471214127 and 1.8927471474569764
distance:-3.2844961471214127 and 1.8927471474569764
distance:-3.2844961471214127 and 1.8927471474569764
distance:-3.2844961471214127 and 1.8927471474569764
distance:-3.2844961471214127 and 1.8927471474569764
distance:-3.2844961471214127 and 1.8927471474569764
distance:-3.2844961471214127 and 1.8927471474569764
distance:-3.2844961471214127 and 1.8927471474569764
distance:-3.2844961471214127 and 1.8927471474569764
distance:-3.2844961471214127 and 1.8927471474569764
distance:-3.2844961471214127 and 1.8927471474569764
distance:-3.2844961471214127 and 1.8927471474569764
distance:-3.2844961471214127 and 1.8927471474569764
distance:-3.2844961471214127 and 1.8927471474569764
distance:-3.2844961471214127 and 1.8927471474569764
distance:-3.2844961471214127 and 1.8927471474569764
distance:-3.2844961471214127 and 1.8927471474569764
distance:-3.2844961471214127 and 1.8927471474569764
distance:-3.

distance:-3.2844961471214127 and 1.8927471474569764
distance:-3.2844961471214127 and 1.8927471474569764
distance:-3.2844961471214127 and 1.8927471474569764
distance:-3.2844961471214127 and 1.8927471474569764
distance:-3.2844961471214127 and 1.8927471474569764
distance:-3.2844961471214127 and 1.8927471474569764
distance:-3.2844961471214127 and 1.8927471474569764
distance:-3.2844961471214127 and 1.8927471474569764
distance:-3.2844961471214127 and 1.8927471474569764
distance:-3.2844961471214127 and 1.8927471474569764
distance:-3.2844961471214127 and 1.8927471474569764
distance:-3.8766434288712333 and 2.230181923240224
distance:-3.2844961471214127 and 1.8927471474569764
distance:-3.2844961471214127 and 1.8927471474569764
distance:-3.2844961471214127 and 1.8927471474569764
distance:-3.2844961471214127 and 1.8927471474569764
distance:-3.2844961471214127 and 1.8927471474569764
distance:-3.2844961471214127 and 1.8927471474569764
distance:-3.2844961471214127 and 1.8927471474569764
distance:-3.2

distance:-3.2844961471214127 and 1.8927471474569764
distance:-3.2844961471214127 and 1.8927471474569764
distance:-3.2844961471214127 and 1.8927471474569764
distance:-3.2844961471214127 and 1.8927471474569764
distance:-3.2844961471214127 and 1.8927471474569764
distance:-3.2844961471214127 and 1.8927471474569764
distance:-3.2844961471214127 and 1.8927471474569764
distance:-3.2844961471214127 and 1.8927471474569764
distance:-3.2844961471214127 and 1.8927471474569764
distance:-3.2844961471214127 and 1.8927471474569764
distance:-3.2844961471214127 and 1.8927471474569764
distance:-3.2844961471214127 and 1.8927471474569764
distance:-3.2844961471214127 and 1.8927471474569764
distance:-3.2844961471214127 and 1.8927471474569764
distance:-3.2844961471214127 and 1.8927471474569764
distance:-3.8766434288712333 and 2.230181923240224
distance:-3.2844961471214127 and 1.8927471474569764
distance:-3.2844961471214127 and 1.8927471474569764
distance:-3.2844961471214127 and 1.8927471474569764
distance:-3.2

distance:-3.960651260904605 and 2.256827791944456
distance:-4.211577638630644 and 2.4002936451053962
distance:-3.960651260904605 and 2.256827791944456
distance:-4.211577638630644 and 2.4002936451053962
distance:-3.8766434288712333 and 2.230181923240224
distance:-3.960651260904605 and 2.256827791944456
distance:-3.960651260904605 and 2.256827791944456
distance:-3.960651260904605 and 2.256827791944456
distance:-3.960651260904605 and 2.256827791944456
distance:-3.960651260904605 and 2.256827791944456
distance:-3.2844961471214127 and 1.8927471474569764
distance:-3.8766434288712333 and 2.230181923240224
distance:-3.8766434288712333 and 2.230181923240224
distance:-4.180047546800516 and 2.390623206914608
distance:-4.180047546800516 and 2.390623206914608
distance:-3.8766434288712333 and 2.230181923240224
distance:-3.960651260904605 and 2.256827791944456
distance:-3.8766434288712333 and 2.230181923240224
distance:-3.2844961471214127 and 1.8927471474569764
distance:-3.2844961471214127 and 1.8927

distance:-3.8766434288712333 and 2.230181923240224
distance:-3.773089388461017 and 2.1832054455598247
distance:-3.960651260904605 and 2.256827791944456
distance:-3.8766434288712333 and 2.230181923240224
distance:-3.8766434288712333 and 2.230181923240224
distance:-3.8766434288712333 and 2.230181923240224
distance:-3.8766434288712333 and 2.230181923240224
distance:-4.134064237787335 and 2.3774848507227517
distance:-3.563295140492766 and 2.0526930182790863
distance:-4.134064237787335 and 2.3774848507227517
distance:-4.211577638630644 and 2.4002936451053962
distance:-4.134064237787335 and 2.3774848507227517
distance:-4.211577638630644 and 2.4002936451053962
distance:-3.563295140492766 and 2.0526930182790863
distance:-3.563295140492766 and 2.0526930182790863
distance:-4.134064237787335 and 2.3774848507227517
distance:-3.563295140492766 and 2.0526930182790863
distance:-4.134064237787335 and 2.3774848507227517
distance:-4.134064237787335 and 2.3774848507227517
distance:-4.134064237787335 and 

distance:-4.149784743369484 and 2.401420857928219
distance:-4.149784743369484 and 2.401420857928219
distance:-4.149784743369484 and 2.401420857928219
distance:-4.149784743369484 and 2.401420857928219
distance:-3.5915074548772914 and 2.0845506351864387
distance:-4.149784743369484 and 2.401420857928219
distance:-3.5915074548772914 and 2.0845506351864387
distance:-3.5915074548772914 and 2.0845506351864387
distance:-4.149784743369484 and 2.401420857928219
distance:-4.149784743369484 and 2.401420857928219
distance:-4.149784743369484 and 2.401420857928219
distance:-4.149784743369484 and 2.401420857928219
distance:-3.5915074548772914 and 2.0845506351864387
distance:-4.149784743369484 and 2.401420857928219
distance:-3.5915074548772914 and 2.0845506351864387
distance:-3.5915074548772914 and 2.0845506351864387
distance:-3.5915074548772914 and 2.0845506351864387
distance:-3.5915074548772914 and 2.0845506351864387
distance:-4.149784743369484 and 2.401420857928219
distance:-4.149784743369484 and 2.

distance:-4.223295425922977 and 2.428853247060111
distance:-4.223295425922977 and 2.428853247060111
distance:-3.2180043249410097 and 1.8064901464149123
distance:-3.2180043249410097 and 1.8064901464149123
distance:-3.2180043249410097 and 1.8064901464149123
distance:-3.2180043249410097 and 1.8064901464149123
distance:-3.2180043249410097 and 1.8064901464149123
distance:-3.2180043249410097 and 1.8064901464149123
distance:-3.2180043249410097 and 1.8064901464149123
distance:-3.578979174267328 and 2.0007695515778394
distance:-3.578979174267328 and 2.0007695515778394
distance:-3.578979174267328 and 2.0007695515778394
distance:-3.2180043249410097 and 1.8064901464149123
distance:-3.578979174267328 and 2.0007695515778394
distance:-3.578979174267328 and 2.0007695515778394
distance:-3.578979174267328 and 2.0007695515778394
distance:-3.578979174267328 and 2.0007695515778394
distance:-3.578979174267328 and 2.0007695515778394
distance:-3.578979174267328 and 2.0007695515778394
distance:-3.5789791742673

distance:-4.223295425922977 and 2.428853247060111
distance:-4.223295425922977 and 2.428853247060111
distance:-4.223295425922977 and 2.428853247060111
distance:-4.223295425922977 and 2.428853247060111
distance:-4.223295425922977 and 2.428853247060111
distance:-4.223295425922977 and 2.428853247060111
distance:-4.223295425922977 and 2.428853247060111
distance:-4.223295425922977 and 2.428853247060111
distance:-4.223295425922977 and 2.428853247060111
distance:-4.223295425922977 and 2.428853247060111
distance:-3.578979174267328 and 2.0007695515778394
distance:-3.578979174267328 and 2.0007695515778394
distance:-3.578979174267328 and 2.0007695515778394
distance:-3.578979174267328 and 2.0007695515778394
distance:-3.578979174267328 and 2.0007695515778394
distance:-3.578979174267328 and 2.0007695515778394
distance:-3.578979174267328 and 2.0007695515778394
distance:-3.578979174267328 and 2.0007695515778394
distance:-3.578979174267328 and 2.0007695515778394
distance:-3.578979174267328 and 2.0007695

distance:-4.223295425922977 and 2.428853247060111
distance:-4.223295425922977 and 2.428853247060111
distance:-4.223295425922977 and 2.428853247060111
distance:-4.223295425922977 and 2.428853247060111
distance:-4.223295425922977 and 2.428853247060111
distance:-4.223295425922977 and 2.428853247060111
distance:-4.223295425922977 and 2.428853247060111
distance:-3.578979174267328 and 2.0007695515778394
distance:-3.2180043249410097 and 1.8064901464149123
distance:-3.2180043249410097 and 1.8064901464149123
distance:-3.2180043249410097 and 1.8064901464149123
distance:-3.2180043249410097 and 1.8064901464149123
distance:-3.2180043249410097 and 1.8064901464149123
distance:-3.2180043249410097 and 1.8064901464149123
distance:-3.2180043249410097 and 1.8064901464149123
distance:-3.2180043249410097 and 1.8064901464149123
distance:-3.2180043249410097 and 1.8064901464149123
distance:-3.2180043249410097 and 1.8064901464149123
distance:-3.2180043249410097 and 1.8064901464149123
distance:-3.218004324941009

distance:-3.2180043249410097 and 1.8064901464149123
distance:-3.2180043249410097 and 1.8064901464149123
distance:-4.223295425922977 and 2.428853247060111
distance:-4.223295425922977 and 2.428853247060111
distance:-3.862335741011499 and 2.225236670248222
distance:-3.862335741011499 and 2.225236670248222
distance:-3.862335741011499 and 2.225236670248222
distance:-3.862335741011499 and 2.225236670248222
distance:-3.2180043249410097 and 1.8064901464149123
distance:-3.578979174267328 and 2.0007695515778394
distance:-3.578979174267328 and 2.0007695515778394
distance:-4.223295425922977 and 2.428853247060111
distance:-4.223295425922977 and 2.428853247060111
distance:-4.223295425922977 and 2.428853247060111
distance:-4.223295425922977 and 2.428853247060111
distance:-4.223295425922977 and 2.428853247060111
distance:-4.223295425922977 and 2.428853247060111
distance:-4.223295425922977 and 2.428853247060111
distance:-4.223295425922977 and 2.428853247060111
distance:-4.223295425922977 and 2.42885324

distance:-3.2180043249410097 and 1.8064901464149123
distance:-3.2180043249410097 and 1.8064901464149123
distance:-3.2180043249410097 and 1.8064901464149123
distance:-3.2180043249410097 and 1.8064901464149123
distance:-3.2180043249410097 and 1.8064901464149123
distance:-3.2180043249410097 and 1.8064901464149123
distance:-3.2180043249410097 and 1.8064901464149123
distance:-3.2180043249410097 and 1.8064901464149123
distance:-3.2180043249410097 and 1.8064901464149123
distance:-3.2180043249410097 and 1.8064901464149123
distance:-3.2180043249410097 and 1.8064901464149123
distance:-3.2180043249410097 and 1.8064901464149123
distance:-3.2180043249410097 and 1.8064901464149123
distance:-3.2180043249410097 and 1.8064901464149123
distance:-3.2180043249410097 and 1.8064901464149123
distance:-3.2180043249410097 and 1.8064901464149123
distance:-3.2180043249410097 and 1.8064901464149123
distance:-3.2180043249410097 and 1.8064901464149123
distance:-3.862335741011499 and 2.225236670248222
distance:-3.21

distance:-3.862335741011499 and 2.225236670248222
distance:-3.862335741011499 and 2.225236670248222
distance:-3.862335741011499 and 2.225236670248222
distance:-4.223295425922977 and 2.428853247060111
distance:-3.862335741011499 and 2.225236670248222
distance:-4.223295425922977 and 2.428853247060111
distance:-4.223295425922977 and 2.428853247060111
distance:-3.862335741011499 and 2.225236670248222
distance:-4.223295425922977 and 2.428853247060111
distance:-3.862335741011499 and 2.225236670248222
distance:-4.223295425922977 and 2.428853247060111
distance:-4.223295425922977 and 2.428853247060111
distance:-3.862335741011499 and 2.225236670248222
distance:-4.223295425922977 and 2.428853247060111
distance:-4.223295425922977 and 2.428853247060111
distance:-4.223295425922977 and 2.428853247060111
distance:-4.223295425922977 and 2.428853247060111
distance:-4.223295425922977 and 2.428853247060111
distance:-4.223295425922977 and 2.428853247060111
distance:-4.223295425922977 and 2.428853247060111


distance:-3.2031775540241476 and 1.8574802321565294
distance:-3.2031775540241476 and 1.8574802321565294
distance:-3.224902657283085 and 1.865162885990351
distance:-3.224902657283085 and 1.865162885990351
distance:-3.2031775540241476 and 1.8574802321565294
distance:-3.224902657283085 and 1.865162885990351
distance:-3.600549834410341 and 2.110014267392419
distance:-3.5788247311514034 and 2.102331613558597
distance:-3.224902657283085 and 1.865162885990351
distance:-3.224902657283085 and 1.865162885990351
distance:-3.5788247311514034 and 2.102331613558597
distance:-3.224902657283085 and 1.865162885990351
distance:-3.600549834410341 and 2.110014267392419
distance:-3.600549834410341 and 2.110014267392419
distance:-3.600549834410341 and 2.110014267392419
distance:-3.600549834410341 and 2.110014267392419
distance:-3.600549834410341 and 2.110014267392419
distance:-3.5788247311514034 and 2.102331613558597
distance:-3.600549834410341 and 2.110014267392419
distance:-3.5788247311514034 and 2.102331

distance:-3.600549834410341 and 2.110014267392419
distance:-3.600549834410341 and 2.110014267392419
distance:-3.600549834410341 and 2.110014267392419
distance:-3.224902657283085 and 1.865162885990351
distance:-3.600549834410341 and 2.110014267392419
distance:-3.600549834410341 and 2.110014267392419
distance:-3.600549834410341 and 2.110014267392419
distance:-3.600549834410341 and 2.110014267392419
distance:-3.2031775540241476 and 1.8574802321565294
distance:-3.600549834410341 and 2.110014267392419
distance:-3.224902657283085 and 1.865162885990351
distance:-3.600549834410341 and 2.110014267392419
distance:-3.600549834410341 and 2.110014267392419
distance:-3.600549834410341 and 2.110014267392419
distance:-3.600549834410341 and 2.110014267392419
distance:-3.600549834410341 and 2.110014267392419
distance:-3.600549834410341 and 2.110014267392419
distance:-3.600549834410341 and 2.110014267392419
distance:-3.600549834410341 and 2.110014267392419
distance:-3.600549834410341 and 2.11001426739241

distance:-4.8781846916817955 and 2.533612730921732
distance:-4.8781846916817955 and 2.533612730921732
distance:-4.8781846916817955 and 2.533612730921732
distance:-4.8781846916817955 and 2.533612730921732
distance:-4.315445860974197 and 2.1438016294776006
distance:-4.315445860974197 and 2.1438016294776006
distance:-5.617107584379323 and 3.0268982745171193
distance:-5.617107584379323 and 3.0268982745171193
distance:-4.8781846916817955 and 2.533612730921732
distance:-5.617107584379323 and 3.0268982745171193
distance:-5.2429336015351 and 2.7780725879678982
distance:-4.403125373075206 and 2.173364884642826
distance:-6.112188920869119 and 3.321397675523375
distance:-4.315445860974197 and 2.1438016294776006
distance:-5.738014938024897 and 3.072571988974154
distance:-4.315445860974197 and 2.1438016294776006
distance:-6.759274181877373 and 3.6731783772272912
distance:-4.403125373075206 and 2.173364884642826
distance:-5.252358674526018 and 2.782438417470953
distance:-5.252358674526018 and 2.7824

distance:-4.68961984381842 and 2.3926273160268217
distance:-4.7216978245254175 and 2.3973285743045807
distance:-4.68961984381842 and 2.3926273160268217
distance:-4.7216978245254175 and 2.3973285743045807
distance:-4.7216978245254175 and 2.3973285743045807
distance:-4.717795140332299 and 2.390907400926146
distance:-4.7216978245254175 and 2.3973285743045807
distance:-4.68961984381842 and 2.3926273160268217
distance:-4.7216978245254175 and 2.3973285743045807
distance:-4.68961984381842 and 2.3926273160268217
distance:-4.68961984381842 and 2.3926273160268217
distance:-4.68961984381842 and 2.3926273160268217
distance:-4.7216978245254175 and 2.3973285743045807
distance:-4.8781846916817955 and 2.533612730921732
distance:-5.178932758925356 and 2.7528908842848274
distance:-4.68961984381842 and 2.3926273160268217
distance:-4.315445860974197 and 2.1438016294776006
distance:-4.717795140332299 and 2.390907400926146
distance:-4.403125373075206 and 2.173364884642826
distance:-4.7216978245254175 and 2.

distance:-4.68961984381842 and 2.3926273160268217
distance:-4.68961984381842 and 2.3926273160268217
distance:-4.754623610341103 and 2.417959525444765
distance:-4.68961984381842 and 2.3926273160268217
distance:-4.7216978245254175 and 2.3973285743045807
distance:-4.68961984381842 and 2.3926273160268217
distance:-4.68961984381842 and 2.3926273160268217
distance:-4.315445860974197 and 2.1438016294776006
distance:-4.7216978245254175 and 2.3973285743045807
distance:-4.7216978245254175 and 2.3973285743045807
distance:-4.7216978245254175 and 2.3973285743045807
distance:-4.7867015910481 and 2.422660783722524
distance:-4.754623610341103 and 2.417959525444765
distance:-4.7867015910481 and 2.422660783722524
distance:-4.754623610341103 and 2.417959525444765
distance:-4.7867015910481 and 2.422660783722524
distance:-4.754623610341103 and 2.417959525444765
distance:-4.754623610341103 and 2.417959525444765
distance:-4.754623610341103 and 2.417959525444765
distance:-4.38044962749688 and 2.16913383889554

distance:-4.754623610341103 and 2.417959525444765
distance:-4.754623610341103 and 2.417959525444765
distance:-4.754623610341103 and 2.417959525444765
distance:-4.7867015910481 and 2.422660783722524
distance:-4.754623610341103 and 2.417959525444765
distance:-4.7867015910481 and 2.422660783722524
distance:-4.754623610341103 and 2.417959525444765
distance:-4.754623610341103 and 2.417959525444765
distance:-4.754623610341103 and 2.417959525444765
distance:-4.754623610341103 and 2.417959525444765
distance:-4.754623610341103 and 2.417959525444765
distance:-4.754623610341103 and 2.417959525444765
distance:-4.754623610341103 and 2.417959525444765
distance:-4.754623610341103 and 2.417959525444765
distance:-4.754623610341103 and 2.417959525444765
distance:-4.754623610341103 and 2.417959525444765
distance:-4.38044962749688 and 2.1691338388955437
distance:-4.754623610341103 and 2.417959525444765
distance:-4.754623610341103 and 2.417959525444765
distance:-4.754623610341103 and 2.417959525444765
dist

distance:-5.828647343477762 and 3.113300676506853
distance:-4.754623610341103 and 2.417959525444765
distance:-4.754623610341103 and 2.417959525444765
distance:-4.754623610341103 and 2.417959525444765
distance:-4.754623610341103 and 2.417959525444765
distance:-4.754623610341103 and 2.417959525444765
distance:-4.754623610341103 and 2.417959525444765
distance:-4.754623610341103 and 2.417959525444765
distance:-4.754623610341103 and 2.417959525444765
distance:-4.754623610341103 and 2.417959525444765
distance:-4.754623610341103 and 2.417959525444765
distance:-4.754623610341103 and 2.417959525444765
distance:-4.754623610341103 and 2.417959525444765
distance:-4.754623610341103 and 2.417959525444765
distance:-4.754623610341103 and 2.417959525444765
distance:-4.754623610341103 and 2.417959525444765
distance:-4.754623610341103 and 2.417959525444765
distance:-4.754623610341103 and 2.417959525444765
distance:-4.754623610341103 and 2.417959525444765
distance:-4.754623610341103 and 2.417959525444765


distance:-5.860725324184759 and 3.118001934784612
distance:-5.860725324184759 and 3.118001934784612
distance:-5.860725324184759 and 3.118001934784612
distance:-5.860725324184759 and 3.118001934784612
distance:-5.860725324184759 and 3.118001934784612
distance:-5.860725324184759 and 3.118001934784612
distance:-5.860725324184759 and 3.118001934784612
distance:-5.860725324184759 and 3.118001934784612
distance:-5.860725324184759 and 3.118001934784612
distance:-5.860725324184759 and 3.118001934784612
distance:-5.860725324184759 and 3.118001934784612
distance:-5.860725324184759 and 3.118001934784612
distance:-5.860725324184759 and 3.118001934784612
distance:-5.860725324184759 and 3.118001934784612
distance:-4.754623610341103 and 2.417959525444765
distance:-4.68961984381842 and 2.3926273160268217
distance:-4.754623610341103 and 2.417959525444765
distance:-4.754623610341103 and 2.417959525444765
distance:-4.754623610341103 and 2.417959525444765
distance:-4.754623610341103 and 2.417959525444765


distance:-5.506875310244919 and 3.261431866983031
distance:-5.7419911302076905 and 3.7938230800136363
distance:-6.340857907046711 and 4.368731541702674
distance:-5.785549692966072 and 4.142618700499424
distance:-6.910131699750586 and 5.08100984711422
distance:-6.574643147103277 and 4.863982901844928
distance:-5.851589241037335 and 4.369281502108985
distance:-6.453569912334611 and 4.803532855092014
distance:-6.4518097155019944 and 5.004927192441663
distance:-6.988868894825487 and 5.499259481187238
distance:-6.90541977893319 and 5.673064019603109
distance:-7.081056293666947 and 5.883360329475664
distance:-7.148121042585949 and 5.80005176210218
distance:-6.62689547206984 and 5.148589233548545
distance:-6.551645250684615 and 4.7036311444011645
distance:-7.376500155306182 and 5.023131247502933
distance:-7.693414986530225 and 5.025084633387241
distance:-7.148176302530441 and 4.291007548927254
distance:-6.976882240573744 and 3.953813921136115
distance:-7.265661896161852 and 3.366021252044046


distance:-10.611179339358191 and -11.243163205119501
distance:-9.692331493298532 and -11.836060271219253
distance:-10.317032680008353 and -11.414528620905632
distance:-10.317032680008353 and -11.414528620905632
distance:-9.692331493298532 and -11.836060271219253
distance:-10.317032680008353 and -11.414528620905632
distance:-10.317032680008353 and -11.414528620905632
distance:-10.317032680008353 and -11.414528620905632
distance:-10.317032680008353 and -11.414528620905632
distance:-10.317032680008353 and -11.414528620905632
distance:-10.317032680008353 and -11.414528620905632
distance:-10.611179339358191 and -11.243163205119501
distance:-10.317032680008353 and -11.414528620905632
distance:-10.317032680008353 and -11.414528620905632
distance:-10.317032680008353 and -11.414528620905632
distance:-10.317032680008353 and -11.414528620905632
distance:-10.317032680008353 and -11.414528620905632
distance:-10.317032680008353 and -11.414528620905632
distance:-10.347883758684908 and -11.33350054032

distance:-10.317032680008353 and -11.414528620905632
distance:-10.317032680008353 and -11.414528620905632
distance:-10.317032680008353 and -11.414528620905632
distance:-10.317032680008353 and -11.414528620905632
distance:-10.317032680008353 and -11.414528620905632
distance:-10.317032680008353 and -11.414528620905632
distance:-10.317032680008353 and -11.414528620905632
distance:-10.317032680008353 and -11.414528620905632
distance:-10.317032680008353 and -11.414528620905632
distance:-10.317032680008353 and -11.414528620905632
distance:-10.347883758684908 and -11.333500540328878
distance:-10.347883758684908 and -11.333500540328878
distance:-10.317032680008353 and -11.414528620905632
distance:-10.317032680008353 and -11.414528620905632
distance:-10.317032680008353 and -11.414528620905632
distance:-10.317032680008353 and -11.414528620905632
distance:-10.347883758684908 and -11.333500540328878
distance:-10.347883758684908 and -11.333500540328878
distance:-10.347883758684908 and -11.333500540

distance:-10.611179339358191 and -11.243163205119501
distance:-10.611179339358191 and -11.243163205119501
distance:-10.611179339358191 and -11.243163205119501
distance:-10.611179339358191 and -11.243163205119501
distance:-10.611179339358191 and -11.243163205119501
distance:-10.611179339358191 and -11.243163205119501
distance:-10.611179339358191 and -11.243163205119501
distance:-10.611179339358191 and -11.243163205119501
distance:-10.611179339358191 and -11.243163205119501
distance:-10.611179339358191 and -11.243163205119501
distance:-10.611179339358191 and -11.243163205119501
distance:-10.611179339358191 and -11.243163205119501
distance:-10.611179339358191 and -11.243163205119501
distance:-10.611179339358191 and -11.243163205119501
distance:-10.611179339358191 and -11.243163205119501
distance:-10.611179339358191 and -11.243163205119501
distance:-10.611179339358191 and -11.243163205119501
distance:-10.611179339358191 and -11.243163205119501
distance:-10.611179339358191 and -11.243163205

distance:-10.611179339358191 and -11.243163205119501
distance:-10.611179339358191 and -11.243163205119501
distance:-11.124181517151502 and -10.572452508499296
distance:-11.124181517151502 and -10.572452508499296
distance:-11.124181517151502 and -10.572452508499296
distance:-11.124181517151502 and -10.572452508499296
distance:-11.124181517151502 and -10.572452508499296
distance:-11.124181517151502 and -10.572452508499296
distance:-11.124181517151502 and -10.572452508499296
distance:-11.124181517151502 and -10.572452508499296
distance:-11.124181517151502 and -10.572452508499296
distance:-10.611179339358191 and -11.243163205119501
distance:-11.124181517151502 and -10.572452508499296
distance:-10.611179339358191 and -11.243163205119501
distance:-10.611179339358191 and -11.243163205119501
distance:-11.124181517151502 and -10.572452508499296
distance:-10.611179339358191 and -11.243163205119501
distance:-11.124181517151502 and -10.572452508499296
distance:-11.124181517151502 and -10.572452508

distance:-11.124181517151502 and -10.572452508499296
distance:-10.317032680008353 and -11.414528620905632
distance:-10.611179339358191 and -11.243163205119501
distance:-10.611179339358191 and -11.243163205119501
distance:-10.611179339358191 and -11.243163205119501
distance:-10.611179339358191 and -11.243163205119501
distance:-10.611179339358191 and -11.243163205119501
distance:-10.611179339358191 and -11.243163205119501
distance:-10.611179339358191 and -11.243163205119501
distance:-10.611179339358191 and -11.243163205119501
distance:-10.611179339358191 and -11.243163205119501
distance:-10.611179339358191 and -11.243163205119501
distance:-10.611179339358191 and -11.243163205119501
distance:-10.317032680008353 and -11.414528620905632
distance:-10.317032680008353 and -11.414528620905632
distance:-10.317032680008353 and -11.414528620905632
distance:-10.317032680008353 and -11.414528620905632
distance:-10.317032680008353 and -11.414528620905632
distance:-10.317032680008353 and -11.414528620

distance:-11.124181517151502 and -10.572452508499296
distance:-11.124181517151502 and -10.572452508499296
distance:-11.124181517151502 and -10.572452508499296
distance:-10.949144169369838 and -10.840803254264646
distance:-10.949144169369838 and -10.840803254264646
distance:-10.949144169369838 and -10.840803254264646
distance:-10.949144169369838 and -10.840803254264646
distance:-11.124181517151502 and -10.572452508499296
distance:-11.124181517151502 and -10.572452508499296
distance:-11.124181517151502 and -10.572452508499296
distance:-10.949144169369838 and -10.840803254264646
distance:-11.124181517151502 and -10.572452508499296
distance:-11.124181517151502 and -10.572452508499296
distance:-11.124181517151502 and -10.572452508499296
distance:-11.415244855301946 and -10.40041668675612
distance:-11.415244855301946 and -10.40041668675612
distance:-11.415244855301946 and -10.40041668675612
distance:-11.415244855301946 and -10.40041668675612
distance:-11.415244855301946 and -10.4004166867561

distance:-11.124181517151502 and -10.572452508499296
distance:-10.761567434538275 and -10.810148276660083
distance:-11.055714093888113 and -10.638782860873953
distance:-10.761567434538275 and -10.810148276660083
distance:-11.04831554429931 and -10.5889754955111
distance:-11.04831554429931 and -10.5889754955111
distance:-10.754168884949472 and -10.76034091129723
distance:-10.754168884949472 and -10.76034091129723
distance:-10.754168884949472 and -10.76034091129723
distance:-10.754168884949472 and -10.76034091129723
distance:-10.754168884949472 and -10.76034091129723
distance:-10.754168884949472 and -10.76034091129723
distance:-10.754168884949472 and -10.76034091129723
distance:-11.055714093888113 and -10.638782860873953
distance:-11.055714093888113 and -10.638782860873953
distance:-11.055714093888113 and -10.638782860873953
distance:-11.055714093888113 and -10.638782860873953
distance:-11.055714093888113 and -10.638782860873953
distance:-11.055714093888113 and -10.638782860873953
distan

distance:-10.67773510972091 and -11.27828197896947
distance:-10.67773510972091 and -11.27828197896947
distance:-10.67773510972091 and -11.27828197896947
distance:-10.67773510972091 and -11.27828197896947
distance:-10.67773510972091 and -11.27828197896947
distance:-10.67773510972091 and -11.27828197896947
distance:-10.67773510972091 and -11.27828197896947
distance:-10.67773510972091 and -11.27828197896947
distance:-10.67773510972091 and -11.27828197896947
distance:-10.67773510972091 and -11.27828197896947
distance:-10.67773510972091 and -11.27828197896947
distance:-11.122269864250832 and -10.673901634723922
distance:-11.122269864250832 and -10.673901634723922
distance:-10.67773510972091 and -11.27828197896947
distance:-10.67773510972091 and -11.27828197896947
distance:-10.67773510972091 and -11.27828197896947
distance:-10.67773510972091 and -11.27828197896947
distance:-10.67773510972091 and -11.27828197896947
distance:-10.67773510972091 and -11.27828197896947
distance:-10.67773510972091

distance:-11.676416073924536 and -8.968567527996822
distance:-11.676416073924536 and -8.968567527996822
distance:-11.676416073924536 and -8.968567527996822
distance:-11.676416073924536 and -8.968567527996822
distance:-11.51763232203886 and -9.165328268810462
distance:-11.51763232203886 and -9.165328268810462
distance:-11.51763232203886 and -9.165328268810462
distance:-11.51763232203886 and -9.165328268810462
distance:-11.51763232203886 and -9.165328268810462
distance:-11.506582862188377 and -9.17658955044283
distance:-11.506582862188377 and -9.17658955044283
distance:-11.665366614074053 and -8.97982880962919
distance:-11.665366614074053 and -8.97982880962919
distance:-11.676416073924536 and -8.968567527996822
distance:-11.51763232203886 and -9.165328268810462
distance:-11.68917422767586 and -8.93320480800719
distance:-11.676416073924536 and -8.968567527996822
distance:-11.68917422767586 and -8.93320480800719
distance:-12.239564601092848 and -8.679277537289135
distance:-12.3983483529785

distance:-12.580580133294799 and -8.23521322018037
distance:-12.411106506729848 and -8.447154076485862
distance:-12.411106506729848 and -8.447154076485862
distance:-12.411106506729848 and -8.447154076485862
distance:-12.411106506729848 and -8.447154076485862
distance:-12.411106506729848 and -8.447154076485862
distance:-12.411106506729848 and -8.447154076485862
distance:-12.411106506729848 and -8.447154076485862
distance:-12.411106506729848 and -8.447154076485862
distance:-12.411106506729848 and -8.447154076485862
distance:-12.411106506729848 and -8.447154076485862
distance:-12.411106506729848 and -8.447154076485862
distance:-12.411106506729848 and -8.447154076485862
distance:-12.239564601092848 and -8.679277537289135
distance:-12.398348352978523 and -8.482516796475494
distance:-12.411106506729848 and -8.447154076485862
distance:-12.398348352978523 and -8.482516796475494
distance:-12.239564601092848 and -8.679277537289135
distance:-12.239564601092848 and -8.679277537289135
distance:-12.

distance:-12.398348352978523 and -8.482516796475494
distance:-12.398348352978523 and -8.482516796475494
distance:-12.398348352978523 and -8.482516796475494
distance:-12.398348352978523 and -8.482516796475494
distance:-12.398348352978523 and -8.482516796475494
distance:-12.398348352978523 and -8.482516796475494
distance:-12.398348352978523 and -8.482516796475494
distance:-12.398348352978523 and -8.482516796475494
distance:-12.398348352978523 and -8.482516796475494
distance:-12.398348352978523 and -8.482516796475494
distance:-12.398348352978523 and -8.482516796475494
distance:-12.398348352978523 and -8.482516796475494
distance:-12.148781381831284 and -8.622226156003752
distance:-12.148781381831284 and -8.622226156003752
distance:-12.398348352978523 and -8.482516796475494
distance:-12.398348352978523 and -8.482516796475494
distance:-12.398348352978523 and -8.482516796475494
distance:-12.398348352978523 and -8.482516796475494
distance:-12.148781381831284 and -8.622226156003752
distance:-12

distance:-13.659601276401975 and -6.758928390570279
distance:-12.398348352978523 and -8.482516796475494
distance:-12.148781381831284 and -8.622226156003752
distance:-12.148781381831284 and -8.622226156003752
distance:-12.148781381831284 and -8.622226156003752
distance:-12.148781381831284 and -8.622226156003752
distance:-12.148781381831284 and -8.622226156003752
distance:-12.148781381831284 and -8.622226156003752
distance:-12.148781381831284 and -8.622226156003752
distance:-12.148781381831284 and -8.622226156003752
distance:-12.148781381831284 and -8.622226156003752
distance:-12.398348352978523 and -8.482516796475494
distance:-12.398348352978523 and -8.482516796475494
distance:-12.398348352978523 and -8.482516796475494
distance:-12.398348352978523 and -8.482516796475494
distance:-12.398348352978523 and -8.482516796475494
distance:-12.398348352978523 and -8.482516796475494
distance:-12.398348352978523 and -8.482516796475494
distance:-12.398348352978523 and -8.482516796475494
distance:-12

distance:-11.31208378752595 and -9.126634744780397
distance:-11.31208378752595 and -9.126634744780397
distance:-11.31208378752595 and -9.126634744780397
distance:-11.406392787071653 and -9.05170418009768
distance:-11.31208378752595 and -9.126634744780397
distance:-11.31208378752595 and -9.126634744780397
distance:-11.31208378752595 and -9.126634744780397
distance:-11.31208378752595 and -9.126634744780397
distance:-11.582147321974347 and -8.942644048834456
distance:-11.31208378752595 and -9.126634744780397
distance:-11.31208378752595 and -9.126634744780397
distance:-11.31208378752595 and -9.126634744780397
distance:-11.31208378752595 and -9.126634744780397
distance:-11.582147321974347 and -8.942644048834456
distance:-11.588624567387928 and -8.804400603802556
distance:-11.858688101836325 and -8.620409907856615
distance:-11.31208378752595 and -9.126634744780397
distance:-11.67645632152005 and -8.86771348415174
distance:-11.67645632152005 and -8.86771348415174
distance:-11.858688101836325 

distance:-11.31208378752595 and -9.126634744780397
distance:-11.31208378752595 and -9.126634744780397
distance:-11.31208378752595 and -9.126634744780397
distance:-11.31208378752595 and -9.126634744780397
distance:-11.31208378752595 and -9.126634744780397
distance:-11.723553859500566 and -8.542445724899299
distance:-11.723553859500566 and -8.542445724899299
distance:-11.31208378752595 and -9.126634744780397
distance:-11.31208378752595 and -9.126634744780397
distance:-11.31208378752595 and -9.126634744780397
distance:-11.582147321974347 and -8.942644048834456
distance:-11.31208378752595 and -9.126634744780397
distance:-11.31208378752595 and -9.126634744780397
distance:-11.31208378752595 and -9.126634744780397
distance:-11.31208378752595 and -9.126634744780397
distance:-11.67645632152005 and -8.86771348415174
distance:-11.406392787071653 and -9.05170418009768
distance:-11.31208378752595 and -9.126634744780397
distance:-11.31208378752595 and -9.126634744780397
distance:-11.31208378752595 a

distance:-11.31208378752595 and -9.126634744780397
distance:-11.31208378752595 and -9.126634744780397
distance:-11.31208378752595 and -9.126634744780397
distance:-11.549444966094512 and -9.00306878766995
distance:-11.31208378752595 and -9.126634744780397
distance:-11.549444966094512 and -9.00306878766995
distance:-11.582147321974347 and -8.942644048834456
distance:-11.773040860104828 and -8.837709092136748
distance:-11.582147321974347 and -8.942644048834456
distance:-11.549444966094512 and -9.00306878766995
distance:-11.31208378752595 and -9.126634744780397
distance:-11.31208378752595 and -9.126634744780397
distance:-11.31208378752595 and -9.126634744780397
distance:-11.31208378752595 and -9.126634744780397
distance:-11.31208378752595 and -9.126634744780397
distance:-11.31208378752595 and -9.126634744780397
distance:-11.31208378752595 and -9.126634744780397
distance:-11.582147321974347 and -8.942644048834456
distance:-11.31208378752595 and -9.126634744780397
distance:-11.58214732197434

distance:-11.54172095930873 and -9.075124820345476
distance:-11.54172095930873 and -9.075124820345476
distance:-11.54172095930873 and -9.075124820345476
distance:-11.54172095930873 and -9.075124820345476
distance:-11.54172095930873 and -9.075124820345476
distance:-11.54172095930873 and -9.075124820345476
distance:-11.54172095930873 and -9.075124820345476
distance:-11.54172095930873 and -9.075124820345476
distance:-11.54172095930873 and -9.075124820345476
distance:-11.54172095930873 and -9.075124820345476
distance:-11.54172095930873 and -9.075124820345476
distance:-11.54172095930873 and -9.075124820345476
distance:-11.54172095930873 and -9.075124820345476
distance:-11.54172095930873 and -9.075124820345476
distance:-11.54172095930873 and -9.075124820345476
distance:-11.54172095930873 and -9.075124820345476
distance:-11.271657424860333 and -9.259115516291416
distance:-11.54172095930873 and -9.075124820345476
distance:-11.54172095930873 and -9.075124820345476
distance:-11.54172095930873 an

distance:-8.348628754833555 and -5.1847164048205485
distance:-8.206440529228193 and -4.7579690506929495
distance:-8.385629166306742 and -4.625435621540898
distance:-9.02245718923108 and -4.04810562857709
distance:-9.141169687738643 and -3.873315974098965
distance:-10.33896644905903 and -3.2542173725342494
distance:-10.062110908615175 and -3.7505096532741824
distance:-9.923066825535003 and -3.936319217887128
distance:-9.923066825535003 and -3.936319217887128
distance:-10.041779324042565 and -3.7615295634090025
distance:-9.600267815441413 and -4.478313729103153
distance:-10.041779324042565 and -3.7615295634090025
distance:-10.067195315722426 and -3.806055795463525
distance:-8.939733692864426 and -4.507062942434274
distance:-9.685933191064755 and -3.448811197936653
distance:-10.315103341997439 and -2.5749525992408593
distance:-9.616659655531024 and -3.23681491588318
distance:-9.937590340684547 and -2.7635079086760896
distance:-10.058114146822092 and -2.4543143387443997
distance:-9.9926060

distance:-4.245433930561674 and 3.234169346395074
distance:-4.3130310059728885 and 3.2581657577639156
distance:-4.245433930561674 and 3.234169346395074
distance:-4.759468505951595 and 3.9333371557164476
distance:-4.759468505951595 and 3.9333371557164476
distance:-4.759468505951595 and 3.9333371557164476
distance:-4.759468505951595 and 3.9333371557164476
distance:-4.3130310059728885 and 3.2581657577639156
distance:-4.3130310059728885 and 3.2581657577639156
distance:-4.3130310059728885 and 3.2581657577639156
distance:-4.3130310059728885 and 3.2581657577639156
distance:-4.3130310059728885 and 3.2581657577639156
distance:-4.3130310059728885 and 3.2581657577639156
distance:-4.3130310059728885 and 3.2581657577639156
distance:-4.3130310059728885 and 3.2581657577639156
distance:-4.134396786918202 and 2.9920023673719065
distance:-4.3130310059728885 and 3.2581657577639156
distance:-4.080742894024979 and 2.952951157677713
distance:-4.3435133107010735 and 3.2880605755485526
distance:-4.34351331070

distance:-4.568198778012533 and 3.718917006286219
distance:-4.080742894024979 and 2.952951157677713
distance:-4.080742894024979 and 2.952951157677713
distance:-4.759468505951595 and 3.9333371557164476
distance:-4.527180394003686 and 3.628122555630245
distance:-4.527180394003686 and 3.628122555630245
distance:-4.759468505951595 and 3.9333371557164476
distance:-4.3130310059728885 and 3.2581657577639156
distance:-4.080742894024979 and 2.952951157677713
distance:-4.8004868899604425 and 4.024131606372421
distance:-4.527180394003686 and 3.628122555630245
distance:-4.568198778012533 and 3.718917006286219
distance:-4.759468505951595 and 3.9333371557164476
distance:-4.527180394003686 and 3.628122555630245
distance:-4.3130310059728885 and 3.2581657577639156
distance:-4.3130310059728885 and 3.2581657577639156
distance:-4.3130310059728885 and 3.2581657577639156
distance:-4.3130310059728885 and 3.2581657577639156
distance:-4.759468505951595 and 3.9333371557164476
distance:-4.759468505951595 and 3.9

distance:-8.627762251647226 and -6.4517361285481165
distance:-10.189164000669109 and -5.212524644414557
distance:-10.549209683771135 and -6.740047445735129
distance:-10.669077717394337 and -6.813521501072419
distance:-10.765526625825157 and -7.219035034086804
distance:-11.13325246612525 and -7.458354862961812
distance:-10.926055547528247 and -7.763218465193152
distance:-11.351247709642479 and -7.967045462986679
distance:-11.130163734939291 and -9.241637492988037
distance:-11.165012869422124 and -9.340889290570448
distance:-11.262238192481515 and -9.441922751007723
distance:-11.070914799975952 and -9.690569801499578
distance:-11.8664195382263 and -9.318246540225907
distance:-12.088062258264063 and -9.274141878305194
distance:-12.088062258264063 and -9.274141878305194
distance:-12.088062258264063 and -9.274141878305194
distance:-12.12908064227291 and -9.18334742764922
distance:-12.088062258264063 and -9.274141878305194
distance:-12.088062258264063 and -9.274141878305194
distance:-12.0880

distance:-12.300591098037966 and -9.498394962749646
distance:-12.300591098037966 and -9.498394962749646
distance:-12.300591098037966 and -9.498394962749646
distance:-12.300591098037966 and -9.498394962749646
distance:-12.300591098037966 and -9.498394962749646
distance:-12.512291373089976 and -9.382088892031614
distance:-12.512291373089976 and -9.382088892031614
distance:-12.512291373089976 and -9.382088892031614
distance:-12.512291373089976 and -9.382088892031614
distance:-12.512291373089976 and -9.382088892031614
distance:-12.512291373089976 and -9.382088892031614
distance:-12.512291373089976 and -9.382088892031614
distance:-12.512291373089976 and -9.382088892031614
distance:-12.512291373089976 and -9.382088892031614
distance:-12.300591098037966 and -9.498394962749646
distance:-12.540287530858656 and -9.308395736533818
distance:-12.300591098037966 and -9.498394962749646
distance:-12.512291373089976 and -9.382088892031614
distance:-12.512291373089976 and -9.382088892031614
distance:-12

distance:-12.300591098037966 and -9.498394962749646
distance:-12.300591098037966 and -9.498394962749646
distance:-12.300591098037966 and -9.498394962749646
distance:-12.328587255806646 and -9.42470180725185
distance:-12.328587255806646 and -9.42470180725185
distance:-12.328587255806646 and -9.42470180725185
distance:-12.328587255806646 and -9.42470180725185
distance:-12.328587255806646 and -9.42470180725185
distance:-12.328587255806646 and -9.42470180725185
distance:-12.540287530858656 and -9.308395736533818
distance:-12.300591098037966 and -9.498394962749646
distance:-12.328587255806646 and -9.42470180725185
distance:-12.328587255806646 and -9.42470180725185
distance:-12.300591098037966 and -9.498394962749646
distance:-12.328587255806646 and -9.42470180725185
distance:-12.328587255806646 and -9.42470180725185
distance:-12.328587255806646 and -9.42470180725185
distance:-12.328587255806646 and -9.42470180725185
distance:-12.328587255806646 and -9.42470180725185
distance:-12.328587255806

distance:-12.328587255806646 and -9.42470180725185
distance:-12.304928303236451 and -9.433824980175622
distance:-12.304928303236451 and -9.433824980175622
distance:-12.304928303236451 and -9.433824980175622
distance:-12.304928303236451 and -9.433824980175622
distance:-12.328587255806646 and -9.42470180725185
distance:-12.304928303236451 and -9.433824980175622
distance:-12.304928303236451 and -9.433824980175622
distance:-12.328587255806646 and -9.42470180725185
distance:-12.328587255806646 and -9.42470180725185
distance:-12.328587255806646 and -9.42470180725185
distance:-12.328587255806646 and -9.42470180725185
distance:-12.328587255806646 and -9.42470180725185
distance:-12.540287530858656 and -9.308395736533818
distance:-12.285928598751308 and -9.47116392495413
distance:-12.146632089164477 and -9.682817896175873
distance:-12.304928303236451 and -9.433824980175622
distance:-12.328587255806646 and -9.42470180725185
distance:-12.304928303236451 and -9.433824980175622
distance:-12.32858725

distance:-12.328587255806646 and -9.42470180725185
distance:-12.328587255806646 and -9.42470180725185
distance:-12.328587255806646 and -9.42470180725185
distance:-12.328587255806646 and -9.42470180725185
distance:-12.328587255806646 and -9.42470180725185
distance:-12.328587255806646 and -9.42470180725185
distance:-12.328587255806646 and -9.42470180725185
distance:-12.328587255806646 and -9.42470180725185
distance:-12.328587255806646 and -9.42470180725185
distance:-12.304928303236451 and -9.433824980175622
distance:-12.304928303236451 and -9.433824980175622
distance:-12.328587255806646 and -9.42470180725185
distance:-12.328587255806646 and -9.42470180725185
distance:-12.304928303236451 and -9.433824980175622
distance:-12.304928303236451 and -9.433824980175622
distance:-12.304928303236451 and -9.433824980175622
distance:-12.304928303236451 and -9.433824980175622
distance:-12.328587255806646 and -9.42470180725185
distance:-12.304928303236451 and -9.433824980175622
distance:-12.30492830323

distance:-12.683914637958495 and -9.148709392491668
distance:-12.512291373089976 and -9.382088892031614
distance:-12.406453155463321 and -9.336595725069166
distance:-12.300591098037966 and -9.498394962749646
distance:-12.549860714325522 and -9.36318592826403
distance:-12.406453155463321 and -9.336595725069166
distance:-12.285928598751308 and -9.47116392495413
distance:-12.419781712035185 and -9.342605960316362
distance:-12.276932145467772 and -9.507518135673418
distance:-12.274301385476608 and -9.480873626958982
distance:-12.285928598751308 and -9.47116392495413
distance:-12.406453155463321 and -9.336595725069166
distance:-12.461009213040676 and -9.25119456733037
distance:-12.304928303236451 and -9.433824980175622
distance:-12.435892011669857 and -9.309737370314767
distance:-12.287629942048472 and -9.486883862206177
distance:-12.422563455097993 and -9.303727135067572
distance:-12.109644580022419 and -9.68593083385245
distance:-12.304928303236451 and -9.433824980175622
distance:-12.6872

NameError: name 'swift' is not defined

In [11]:
cv2.destroyAllWindows()